# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/new/system.xdc

# Block Designs: bd/hardware/hardware.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hardware || ORIG_REF_NAME==hardware} -quiet] -quiet

# IP: bd/hardware/ip/hardware_zynq_ultra_ps_e_0_0/hardware_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hardware_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==hardware_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/hardware/ip/hardware_proc_sys_reset_0_0/hardware_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hardware_proc_sys_reset_0_0 || ORIG_REF_NAME==hardware_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/hardware/ip/hardware_proc_sys_reset_1_0/hardware_proc_sys_reset_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hardware_proc_sys_reset_1_0 || ORIG_REF_NAME==hardware_proc_sys_reset_1_0} -quiet] -quiet

# IP: bd/hardware/ip/hardware_proc_sys_reset_1_1/hardware_proc_sys_reset_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hardware_proc_sys_reset_1_1 || ORIG_REF_NAME==hardware_proc_sys_reset_1_1} -quiet] -quiet

# IP: bd/hardware/ip/hardware_axi_intc_0_0/hardware_axi_intc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hardware_axi_intc_0_0 || ORIG_REF_NAME==hardware_axi_intc_0_0} -quiet] -quiet

# IP: bd/hardware/ip/hardware_axi_interconnect_0_0/hardware_axi_interconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hardware_axi_interconnect_0_0 || ORIG_REF_NAME==hardware_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/hardware/ip/hardware_xbar_0/hardware_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hardware_xbar_0 || ORIG_REF_NAME==hardware_xbar_0} -quiet] -quiet

# IP: bd/hardware/ip/hardware_auto_pc_0/hardware_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hardware_auto_pc_0 || ORIG_REF_NAME==hardware_auto_pc_0} -quiet] -quiet

# IP: bd/hardware/ip/hardware_auto_pc_1/hardware_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hardware_auto_pc_1 || ORIG_REF_NAME==hardware_auto_pc_1} -quiet] -quiet

# IP: bd/hardware/ip/hardware_auto_pc_2/hardware_auto_pc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hardware_auto_pc_2 || ORIG_REF_NAME==hardware_auto_pc_2} -quiet] -quiet

# IP: bd/hardware/ip/hardware_axi_interconnect_1_0/hardware_axi_interconnect_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hardware_axi_interconnect_1_0 || ORIG_REF_NAME==hardware_axi_interconnect_1_0} -quiet] -quiet

# IP: bd/hardware/ip/hardware_system_management_wiz_0_0/hardware_system_management_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hardware_system_management_wiz_0_0 || ORIG_REF_NAME==hardware_system_management_wiz_0_0} -quiet] -quiet

# IP: bd/hardware/ip/hardware_temp2pwm_0_0/hardware_temp2pwm_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hardware_temp2pwm_0_0 || ORIG_REF_NAME==hardware_temp2pwm_0_0} -quiet] -quiet

# IP: bd/hardware/ip/hardware_divider_0_0/hardware_divider_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hardware_divider_0_0 || ORIG_REF_NAME==hardware_divider_0_0} -quiet] -quiet

# IP: bd/hardware/ip/hardware_pwm_0_0/hardware_pwm_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hardware_pwm_0_0 || ORIG_REF_NAME==hardware_pwm_0_0} -quiet] -quiet

# IP: bd/hardware/ip/hardware_axi_gpio_0_0/hardware_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hardware_axi_gpio_0_0 || ORIG_REF_NAME==hardware_axi_gpio_0_0} -quiet] -quiet

# IP: bd/hardware/ip/hardware_xlslice_0_0/hardware_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hardware_xlslice_0_0 || ORIG_REF_NAME==hardware_xlslice_0_0} -quiet] -quiet

# IP: bd/hardware/ip/hardware_cmd_bits_0/hardware_cmd_bits_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hardware_cmd_bits_0 || ORIG_REF_NAME==hardware_cmd_bits_0} -quiet] -quiet

# IP: bd/hardware/ip/hardware_cmd_bits_1/hardware_cmd_bits_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hardware_cmd_bits_1 || ORIG_REF_NAME==hardware_cmd_bits_1} -quiet] -quiet

# IP: bd/hardware/ip/hardware_divider_0_1/hardware_divider_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hardware_divider_0_1 || ORIG_REF_NAME==hardware_divider_0_1} -quiet] -quiet

# IP: bd/hardware/ip/hardware_stepper_0_0/hardware_stepper_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hardware_stepper_0_0 || ORIG_REF_NAME==hardware_stepper_0_0} -quiet] -quiet

# IP: bd/hardware/ip/hardware_xlconcat_0_0/hardware_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hardware_xlconcat_0_0 || ORIG_REF_NAME==hardware_xlconcat_0_0} -quiet] -quiet

# IP: bd/hardware/ip/hardware_xlconcat_3_0/hardware_xlconcat_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hardware_xlconcat_3_0 || ORIG_REF_NAME==hardware_xlconcat_3_0} -quiet] -quiet

# IP: bd/hardware/ip/hardware_DPUCZDX8G_0_1/hardware_DPUCZDX8G_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hardware_DPUCZDX8G_0_1 || ORIG_REF_NAME==hardware_DPUCZDX8G_0_1} -quiet] -quiet

# IP: bd/hardware/ip/hardware_clk_wiz_0_2/hardware_clk_wiz_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hardware_clk_wiz_0_2 || ORIG_REF_NAME==hardware_clk_wiz_0_2} -quiet] -quiet

# IP: bd/hardware/ip/hardware_clk_wiz_1_0/hardware_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hardware_clk_wiz_1_0 || ORIG_REF_NAME==hardware_clk_wiz_1_0} -quiet] -quiet

# XDC: /home/mateusz/KV260/hardware/hardware.gen/sources_1/bd/hardware/hardware_ooc.xdc
