# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/system.xdc

# Block Designs: bd/system/system.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system} -quiet] -quiet

# IP: bd/system/ip/system_zynq_ps_0_1/system_zynq_ps_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_zynq_ps_0 || ORIG_REF_NAME==system_zynq_ps_0} -quiet] -quiet

# IP: bd/system/ip/system_clk_wiz_0_1/system_clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_clk_wiz_0 || ORIG_REF_NAME==system_clk_wiz_0} -quiet] -quiet

# IP: bd/system/ip/system_sys_ret200_0_1/system_sys_ret200_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_sys_ret200_0 || ORIG_REF_NAME==system_sys_ret200_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_intc_0_1/system_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_intc_0 || ORIG_REF_NAME==system_axi_intc_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_inter_0_2/system_axi_inter_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_inter_0 || ORIG_REF_NAME==system_axi_inter_0} -quiet] -quiet

# IP: bd/system/ip/system_stepper_div_0_1/system_stepper_div_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_stepper_div_0 || ORIG_REF_NAME==system_stepper_div_0} -quiet] -quiet

# IP: bd/system/ip/system_stepper_0_1/system_stepper_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_stepper_0 || ORIG_REF_NAME==system_stepper_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_io_0_1/system_axi_io_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_io_0 || ORIG_REF_NAME==system_axi_io_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_i2c_0_1/system_axi_i2c_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_i2c_0 || ORIG_REF_NAME==system_axi_i2c_0} -quiet] -quiet

# IP: bd/system/ip/system_latch_bit_0_1/system_latch_bit_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_latch_bit_0 || ORIG_REF_NAME==system_latch_bit_0} -quiet] -quiet

# IP: bd/system/ip/system_cmd_bit_0_1/system_cmd_bit_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_cmd_bit_0 || ORIG_REF_NAME==system_cmd_bit_0} -quiet] -quiet

# IP: bd/system/ip/system_fce_ena_bit_0_1/system_fce_ena_bit_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_fce_ena_bit_0 || ORIG_REF_NAME==system_fce_ena_bit_0} -quiet] -quiet

# IP: bd/system/ip/system_stepper_state_0_1/system_stepper_state_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_stepper_state_0 || ORIG_REF_NAME==system_stepper_state_0} -quiet] -quiet

# IP: bd/system/ip/system_xbar_0_1/system_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_xbar_0 || ORIG_REF_NAME==system_xbar_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_inter1_0_1/system_axi_inter1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_inter1_0 || ORIG_REF_NAME==system_axi_inter1_0} -quiet] -quiet

# IP: bd/system/ip/system_divider_0_0/system_divider_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_divider_0_0 || ORIG_REF_NAME==system_divider_0_0} -quiet] -quiet

# IP: bd/system/ip/system_pwm_0_0/system_pwm_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_pwm_0_0 || ORIG_REF_NAME==system_pwm_0_0} -quiet] -quiet

# IP: bd/system/ip/system_temp2pwm_0_0/system_temp2pwm_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_temp2pwm_0_0 || ORIG_REF_NAME==system_temp2pwm_0_0} -quiet] -quiet

# IP: bd/system/ip/system_system_management_wiz_0_0/system_system_management_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_system_management_wiz_0_0 || ORIG_REF_NAME==system_system_management_wiz_0_0} -quiet] -quiet

# IP: bd/system/ip/system_auto_pc_0_2/system_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_auto_pc_0 || ORIG_REF_NAME==system_auto_pc_0} -quiet] -quiet

# IP: bd/system/ip/system_s00_mmu_0/system_s00_mmu_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_s00_mmu_0 || ORIG_REF_NAME==system_s00_mmu_0} -quiet] -quiet

# XDC: /home/mateusz/KV260/hardware/hardware.gen/sources_1/bd/system/ip/system_zynq_ps_0_1/system_zynq_ps_0_ooc.xdc

# XDC: /home/mateusz/KV260/hardware/hardware.gen/sources_1/bd/system/ip/system_zynq_ps_0_1/system_zynq_ps_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_zynq_ps_0 || ORIG_REF_NAME==system_zynq_ps_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/mateusz/KV260/hardware/hardware.gen/sources_1/bd/system/ip/system_clk_wiz_0_1/system_clk_wiz_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_clk_wiz_0 || ORIG_REF_NAME==system_clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/mateusz/KV260/hardware/hardware.gen/sources_1/bd/system/ip/system_clk_wiz_0_1/system_clk_wiz_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_clk_wiz_0 || ORIG_REF_NAME==system_clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/mateusz/KV260/hardware/hardware.gen/sources_1/bd/system/ip/system_clk_wiz_0_1/system_clk_wiz_0_ooc.xdc

# XDC: /home/mateusz/KV260/hardware/hardware.gen/sources_1/bd/system/ip/system_sys_ret200_0_1/system_sys_ret200_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_sys_ret200_0 || ORIG_REF_NAME==system_sys_ret200_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/mateusz/KV260/hardware/hardware.gen/sources_1/bd/system/ip/system_sys_ret200_0_1/system_sys_ret200_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_sys_ret200_0 || ORIG_REF_NAME==system_sys_ret200_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/mateusz/KV260/hardware/hardware.gen/sources_1/bd/system/ip/system_axi_intc_0_1/system_axi_intc_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_intc_0 || ORIG_REF_NAME==system_axi_intc_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/mateusz/KV260/hardware/hardware.gen/sources_1/bd/system/ip/system_axi_intc_0_1/system_axi_intc_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_intc_0 || ORIG_REF_NAME==system_axi_intc_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/mateusz/KV260/hardware/hardware.gen/sources_1/bd/system/ip/system_axi_intc_0_1/system_axi_intc_0_ooc.xdc

# XDC: /home/mateusz/KV260/hardware/hardware.gen/sources_1/bd/system/ip/system_axi_io_0_1/system_axi_io_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_io_0 || ORIG_REF_NAME==system_axi_io_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/mateusz/KV260/hardware/hardware.gen/sources_1/bd/system/ip/system_axi_io_0_1/system_axi_io_0_ooc.xdc

# XDC: /home/mateusz/KV260/hardware/hardware.gen/sources_1/bd/system/ip/system_axi_io_0_1/system_axi_io_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_io_0 || ORIG_REF_NAME==system_axi_io_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/mateusz/KV260/hardware/hardware.gen/sources_1/bd/system/ip/system_axi_i2c_0_1/system_axi_i2c_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_i2c_0 || ORIG_REF_NAME==system_axi_i2c_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/mateusz/KV260/hardware/hardware.gen/sources_1/bd/system/ip/system_axi_i2c_0_1/system_axi_i2c_0_ooc.xdc

# XDC: /home/mateusz/KV260/hardware/hardware.gen/sources_1/bd/system/ip/system_system_management_wiz_0_0/system_system_management_wiz_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_system_management_wiz_0_0 || ORIG_REF_NAME==system_system_management_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/mateusz/KV260/hardware/hardware.gen/sources_1/bd/system/ip/system_system_management_wiz_0_0/system_system_management_wiz_0_0_ooc.xdc

# XDC: /home/mateusz/KV260/hardware/hardware.gen/sources_1/bd/system/ip/system_system_management_wiz_0_0/system_system_management_wiz_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_system_management_wiz_0_0 || ORIG_REF_NAME==system_system_management_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/mateusz/KV260/hardware/hardware.gen/sources_1/bd/system/ip/system_auto_pc_0_2/system_auto_pc_0_ooc.xdc

# XDC: /home/mateusz/KV260/hardware/hardware.gen/sources_1/bd/system/system_ooc.xdc
