set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR aarch64)
set(CMAKE_SYSROOT /home/mateusz/KV260/package/sdk/sysroots/cortexa72-cortexa53-xilinx-linux)
set(CMAKE_C_COMPILER aarch64-linux-gnu-gcc)
set(CMAKE_CXX_COMPILER aarch64-linux-gnu-g++)
#set(CMAKE_FIND_ROOT_PATH ../../sdk/sysroots/cortexa72-cortexa53-xilinx-linux)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
#set(PYTHON_SOABI cpython-36m-aarch64-linux-gnu)
#set(THREADS_PTHREAD_ARG "0" CACHE STRING "Result from TRY_RUN" FORCE)
set(OPENSSL_CRYPTO_LIBRARY)
set(OPENSSL_INCLUDE_DIR)
