# This file was automatically generated by Vpl
if { ![info exists _is_init_cmds] } {
  source ../../../.local/vpl_init.tcl
  source $local_dir/ocl_util.tcl
  source $local_dir/platform.tcl
  source $local_dir/debug_profile_hooks.tcl
  namespace import ocl_util::*

  set _is_init_cmds true
}



# run timing analysis and frequency scaling
if { ![report_timing_and_scale_freq "" "dr" $vivado_output_dir $vpl_output_dir "kernel_clock_freqs {} system_clock_freqs {} worst_negative_slack 0 max_frequency 650 min_frequency 10 error_on_hold_violation true skip_timing_and_scaling true enable_auto_freq_scale false" "vadd_container"] } {
  return false
}
