// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.1 (64-bit)
// Version: 2021.1
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="krnl_vadd_krnl_vadd,hls_ip_2021_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xck26-sfvc784-2LV-c,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=3.734000,HLS_SYN_LAT=2937,HLS_SYN_TPT=none,HLS_SYN_MEM=5,HLS_SYN_DSP=0,HLS_SYN_FF=1559,HLS_SYN_LUT=3377,HLS_VERSION=2021_1}" *)

module krnl_vadd (
        ap_clk,
        ap_rst_n,
        m_axi_gmem_AWVALID,
        m_axi_gmem_AWREADY,
        m_axi_gmem_AWADDR,
        m_axi_gmem_AWID,
        m_axi_gmem_AWLEN,
        m_axi_gmem_AWSIZE,
        m_axi_gmem_AWBURST,
        m_axi_gmem_AWLOCK,
        m_axi_gmem_AWCACHE,
        m_axi_gmem_AWPROT,
        m_axi_gmem_AWQOS,
        m_axi_gmem_AWREGION,
        m_axi_gmem_AWUSER,
        m_axi_gmem_WVALID,
        m_axi_gmem_WREADY,
        m_axi_gmem_WDATA,
        m_axi_gmem_WSTRB,
        m_axi_gmem_WLAST,
        m_axi_gmem_WID,
        m_axi_gmem_WUSER,
        m_axi_gmem_ARVALID,
        m_axi_gmem_ARREADY,
        m_axi_gmem_ARADDR,
        m_axi_gmem_ARID,
        m_axi_gmem_ARLEN,
        m_axi_gmem_ARSIZE,
        m_axi_gmem_ARBURST,
        m_axi_gmem_ARLOCK,
        m_axi_gmem_ARCACHE,
        m_axi_gmem_ARPROT,
        m_axi_gmem_ARQOS,
        m_axi_gmem_ARREGION,
        m_axi_gmem_ARUSER,
        m_axi_gmem_RVALID,
        m_axi_gmem_RREADY,
        m_axi_gmem_RDATA,
        m_axi_gmem_RLAST,
        m_axi_gmem_RID,
        m_axi_gmem_RUSER,
        m_axi_gmem_RRESP,
        m_axi_gmem_BVALID,
        m_axi_gmem_BREADY,
        m_axi_gmem_BRESP,
        m_axi_gmem_BID,
        m_axi_gmem_BUSER,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 214'd1;
parameter    ap_ST_fsm_state2 = 214'd2;
parameter    ap_ST_fsm_state3 = 214'd4;
parameter    ap_ST_fsm_state4 = 214'd8;
parameter    ap_ST_fsm_state5 = 214'd16;
parameter    ap_ST_fsm_state6 = 214'd32;
parameter    ap_ST_fsm_state7 = 214'd64;
parameter    ap_ST_fsm_state8 = 214'd128;
parameter    ap_ST_fsm_state9 = 214'd256;
parameter    ap_ST_fsm_state10 = 214'd512;
parameter    ap_ST_fsm_state11 = 214'd1024;
parameter    ap_ST_fsm_state12 = 214'd2048;
parameter    ap_ST_fsm_state13 = 214'd4096;
parameter    ap_ST_fsm_state14 = 214'd8192;
parameter    ap_ST_fsm_state15 = 214'd16384;
parameter    ap_ST_fsm_state16 = 214'd32768;
parameter    ap_ST_fsm_state17 = 214'd65536;
parameter    ap_ST_fsm_state18 = 214'd131072;
parameter    ap_ST_fsm_state19 = 214'd262144;
parameter    ap_ST_fsm_state20 = 214'd524288;
parameter    ap_ST_fsm_state21 = 214'd1048576;
parameter    ap_ST_fsm_state22 = 214'd2097152;
parameter    ap_ST_fsm_state23 = 214'd4194304;
parameter    ap_ST_fsm_state24 = 214'd8388608;
parameter    ap_ST_fsm_state25 = 214'd16777216;
parameter    ap_ST_fsm_state26 = 214'd33554432;
parameter    ap_ST_fsm_state27 = 214'd67108864;
parameter    ap_ST_fsm_state28 = 214'd134217728;
parameter    ap_ST_fsm_state29 = 214'd268435456;
parameter    ap_ST_fsm_state30 = 214'd536870912;
parameter    ap_ST_fsm_state31 = 214'd1073741824;
parameter    ap_ST_fsm_state32 = 214'd2147483648;
parameter    ap_ST_fsm_state33 = 214'd4294967296;
parameter    ap_ST_fsm_state34 = 214'd8589934592;
parameter    ap_ST_fsm_state35 = 214'd17179869184;
parameter    ap_ST_fsm_state36 = 214'd34359738368;
parameter    ap_ST_fsm_state37 = 214'd68719476736;
parameter    ap_ST_fsm_state38 = 214'd137438953472;
parameter    ap_ST_fsm_state39 = 214'd274877906944;
parameter    ap_ST_fsm_state40 = 214'd549755813888;
parameter    ap_ST_fsm_state41 = 214'd1099511627776;
parameter    ap_ST_fsm_state42 = 214'd2199023255552;
parameter    ap_ST_fsm_state43 = 214'd4398046511104;
parameter    ap_ST_fsm_state44 = 214'd8796093022208;
parameter    ap_ST_fsm_state45 = 214'd17592186044416;
parameter    ap_ST_fsm_state46 = 214'd35184372088832;
parameter    ap_ST_fsm_state47 = 214'd70368744177664;
parameter    ap_ST_fsm_state48 = 214'd140737488355328;
parameter    ap_ST_fsm_state49 = 214'd281474976710656;
parameter    ap_ST_fsm_state50 = 214'd562949953421312;
parameter    ap_ST_fsm_state51 = 214'd1125899906842624;
parameter    ap_ST_fsm_state52 = 214'd2251799813685248;
parameter    ap_ST_fsm_state53 = 214'd4503599627370496;
parameter    ap_ST_fsm_state54 = 214'd9007199254740992;
parameter    ap_ST_fsm_state55 = 214'd18014398509481984;
parameter    ap_ST_fsm_state56 = 214'd36028797018963968;
parameter    ap_ST_fsm_state57 = 214'd72057594037927936;
parameter    ap_ST_fsm_state58 = 214'd144115188075855872;
parameter    ap_ST_fsm_state59 = 214'd288230376151711744;
parameter    ap_ST_fsm_state60 = 214'd576460752303423488;
parameter    ap_ST_fsm_state61 = 214'd1152921504606846976;
parameter    ap_ST_fsm_state62 = 214'd2305843009213693952;
parameter    ap_ST_fsm_state63 = 214'd4611686018427387904;
parameter    ap_ST_fsm_state64 = 214'd9223372036854775808;
parameter    ap_ST_fsm_state65 = 214'd18446744073709551616;
parameter    ap_ST_fsm_state66 = 214'd36893488147419103232;
parameter    ap_ST_fsm_state67 = 214'd73786976294838206464;
parameter    ap_ST_fsm_state68 = 214'd147573952589676412928;
parameter    ap_ST_fsm_state69 = 214'd295147905179352825856;
parameter    ap_ST_fsm_state70 = 214'd590295810358705651712;
parameter    ap_ST_fsm_state71 = 214'd1180591620717411303424;
parameter    ap_ST_fsm_state72 = 214'd2361183241434822606848;
parameter    ap_ST_fsm_state73 = 214'd4722366482869645213696;
parameter    ap_ST_fsm_state74 = 214'd9444732965739290427392;
parameter    ap_ST_fsm_state75 = 214'd18889465931478580854784;
parameter    ap_ST_fsm_state76 = 214'd37778931862957161709568;
parameter    ap_ST_fsm_state77 = 214'd75557863725914323419136;
parameter    ap_ST_fsm_state78 = 214'd151115727451828646838272;
parameter    ap_ST_fsm_state79 = 214'd302231454903657293676544;
parameter    ap_ST_fsm_state80 = 214'd604462909807314587353088;
parameter    ap_ST_fsm_state81 = 214'd1208925819614629174706176;
parameter    ap_ST_fsm_state82 = 214'd2417851639229258349412352;
parameter    ap_ST_fsm_state83 = 214'd4835703278458516698824704;
parameter    ap_ST_fsm_state84 = 214'd9671406556917033397649408;
parameter    ap_ST_fsm_state85 = 214'd19342813113834066795298816;
parameter    ap_ST_fsm_state86 = 214'd38685626227668133590597632;
parameter    ap_ST_fsm_state87 = 214'd77371252455336267181195264;
parameter    ap_ST_fsm_state88 = 214'd154742504910672534362390528;
parameter    ap_ST_fsm_state89 = 214'd309485009821345068724781056;
parameter    ap_ST_fsm_state90 = 214'd618970019642690137449562112;
parameter    ap_ST_fsm_state91 = 214'd1237940039285380274899124224;
parameter    ap_ST_fsm_state92 = 214'd2475880078570760549798248448;
parameter    ap_ST_fsm_state93 = 214'd4951760157141521099596496896;
parameter    ap_ST_fsm_state94 = 214'd9903520314283042199192993792;
parameter    ap_ST_fsm_state95 = 214'd19807040628566084398385987584;
parameter    ap_ST_fsm_state96 = 214'd39614081257132168796771975168;
parameter    ap_ST_fsm_state97 = 214'd79228162514264337593543950336;
parameter    ap_ST_fsm_state98 = 214'd158456325028528675187087900672;
parameter    ap_ST_fsm_state99 = 214'd316912650057057350374175801344;
parameter    ap_ST_fsm_state100 = 214'd633825300114114700748351602688;
parameter    ap_ST_fsm_state101 = 214'd1267650600228229401496703205376;
parameter    ap_ST_fsm_state102 = 214'd2535301200456458802993406410752;
parameter    ap_ST_fsm_state103 = 214'd5070602400912917605986812821504;
parameter    ap_ST_fsm_state104 = 214'd10141204801825835211973625643008;
parameter    ap_ST_fsm_state105 = 214'd20282409603651670423947251286016;
parameter    ap_ST_fsm_state106 = 214'd40564819207303340847894502572032;
parameter    ap_ST_fsm_state107 = 214'd81129638414606681695789005144064;
parameter    ap_ST_fsm_state108 = 214'd162259276829213363391578010288128;
parameter    ap_ST_fsm_state109 = 214'd324518553658426726783156020576256;
parameter    ap_ST_fsm_state110 = 214'd649037107316853453566312041152512;
parameter    ap_ST_fsm_state111 = 214'd1298074214633706907132624082305024;
parameter    ap_ST_fsm_state112 = 214'd2596148429267413814265248164610048;
parameter    ap_ST_fsm_state113 = 214'd5192296858534827628530496329220096;
parameter    ap_ST_fsm_state114 = 214'd10384593717069655257060992658440192;
parameter    ap_ST_fsm_state115 = 214'd20769187434139310514121985316880384;
parameter    ap_ST_fsm_state116 = 214'd41538374868278621028243970633760768;
parameter    ap_ST_fsm_state117 = 214'd83076749736557242056487941267521536;
parameter    ap_ST_fsm_state118 = 214'd166153499473114484112975882535043072;
parameter    ap_ST_fsm_state119 = 214'd332306998946228968225951765070086144;
parameter    ap_ST_fsm_state120 = 214'd664613997892457936451903530140172288;
parameter    ap_ST_fsm_state121 = 214'd1329227995784915872903807060280344576;
parameter    ap_ST_fsm_state122 = 214'd2658455991569831745807614120560689152;
parameter    ap_ST_fsm_state123 = 214'd5316911983139663491615228241121378304;
parameter    ap_ST_fsm_state124 = 214'd10633823966279326983230456482242756608;
parameter    ap_ST_fsm_state125 = 214'd21267647932558653966460912964485513216;
parameter    ap_ST_fsm_state126 = 214'd42535295865117307932921825928971026432;
parameter    ap_ST_fsm_state127 = 214'd85070591730234615865843651857942052864;
parameter    ap_ST_fsm_state128 = 214'd170141183460469231731687303715884105728;
parameter    ap_ST_fsm_state129 = 214'd340282366920938463463374607431768211456;
parameter    ap_ST_fsm_state130 = 214'd680564733841876926926749214863536422912;
parameter    ap_ST_fsm_state131 = 214'd1361129467683753853853498429727072845824;
parameter    ap_ST_fsm_state132 = 214'd2722258935367507707706996859454145691648;
parameter    ap_ST_fsm_state133 = 214'd5444517870735015415413993718908291383296;
parameter    ap_ST_fsm_state134 = 214'd10889035741470030830827987437816582766592;
parameter    ap_ST_fsm_state135 = 214'd21778071482940061661655974875633165533184;
parameter    ap_ST_fsm_state136 = 214'd43556142965880123323311949751266331066368;
parameter    ap_ST_fsm_state137 = 214'd87112285931760246646623899502532662132736;
parameter    ap_ST_fsm_state138 = 214'd174224571863520493293247799005065324265472;
parameter    ap_ST_fsm_state139 = 214'd348449143727040986586495598010130648530944;
parameter    ap_ST_fsm_state140 = 214'd696898287454081973172991196020261297061888;
parameter    ap_ST_fsm_state141 = 214'd1393796574908163946345982392040522594123776;
parameter    ap_ST_fsm_state142 = 214'd2787593149816327892691964784081045188247552;
parameter    ap_ST_fsm_state143 = 214'd5575186299632655785383929568162090376495104;
parameter    ap_ST_fsm_state144 = 214'd11150372599265311570767859136324180752990208;
parameter    ap_ST_fsm_state145 = 214'd22300745198530623141535718272648361505980416;
parameter    ap_ST_fsm_state146 = 214'd44601490397061246283071436545296723011960832;
parameter    ap_ST_fsm_state147 = 214'd89202980794122492566142873090593446023921664;
parameter    ap_ST_fsm_state148 = 214'd178405961588244985132285746181186892047843328;
parameter    ap_ST_fsm_state149 = 214'd356811923176489970264571492362373784095686656;
parameter    ap_ST_fsm_state150 = 214'd713623846352979940529142984724747568191373312;
parameter    ap_ST_fsm_state151 = 214'd1427247692705959881058285969449495136382746624;
parameter    ap_ST_fsm_state152 = 214'd2854495385411919762116571938898990272765493248;
parameter    ap_ST_fsm_state153 = 214'd5708990770823839524233143877797980545530986496;
parameter    ap_ST_fsm_state154 = 214'd11417981541647679048466287755595961091061972992;
parameter    ap_ST_fsm_state155 = 214'd22835963083295358096932575511191922182123945984;
parameter    ap_ST_fsm_state156 = 214'd45671926166590716193865151022383844364247891968;
parameter    ap_ST_fsm_state157 = 214'd91343852333181432387730302044767688728495783936;
parameter    ap_ST_fsm_state158 = 214'd182687704666362864775460604089535377456991567872;
parameter    ap_ST_fsm_state159 = 214'd365375409332725729550921208179070754913983135744;
parameter    ap_ST_fsm_state160 = 214'd730750818665451459101842416358141509827966271488;
parameter    ap_ST_fsm_state161 = 214'd1461501637330902918203684832716283019655932542976;
parameter    ap_ST_fsm_state162 = 214'd2923003274661805836407369665432566039311865085952;
parameter    ap_ST_fsm_state163 = 214'd5846006549323611672814739330865132078623730171904;
parameter    ap_ST_fsm_state164 = 214'd11692013098647223345629478661730264157247460343808;
parameter    ap_ST_fsm_state165 = 214'd23384026197294446691258957323460528314494920687616;
parameter    ap_ST_fsm_state166 = 214'd46768052394588893382517914646921056628989841375232;
parameter    ap_ST_fsm_state167 = 214'd93536104789177786765035829293842113257979682750464;
parameter    ap_ST_fsm_state168 = 214'd187072209578355573530071658587684226515959365500928;
parameter    ap_ST_fsm_state169 = 214'd374144419156711147060143317175368453031918731001856;
parameter    ap_ST_fsm_state170 = 214'd748288838313422294120286634350736906063837462003712;
parameter    ap_ST_fsm_state171 = 214'd1496577676626844588240573268701473812127674924007424;
parameter    ap_ST_fsm_state172 = 214'd2993155353253689176481146537402947624255349848014848;
parameter    ap_ST_fsm_state173 = 214'd5986310706507378352962293074805895248510699696029696;
parameter    ap_ST_fsm_state174 = 214'd11972621413014756705924586149611790497021399392059392;
parameter    ap_ST_fsm_state175 = 214'd23945242826029513411849172299223580994042798784118784;
parameter    ap_ST_fsm_state176 = 214'd47890485652059026823698344598447161988085597568237568;
parameter    ap_ST_fsm_state177 = 214'd95780971304118053647396689196894323976171195136475136;
parameter    ap_ST_fsm_state178 = 214'd191561942608236107294793378393788647952342390272950272;
parameter    ap_ST_fsm_state179 = 214'd383123885216472214589586756787577295904684780545900544;
parameter    ap_ST_fsm_state180 = 214'd766247770432944429179173513575154591809369561091801088;
parameter    ap_ST_fsm_state181 = 214'd1532495540865888858358347027150309183618739122183602176;
parameter    ap_ST_fsm_state182 = 214'd3064991081731777716716694054300618367237478244367204352;
parameter    ap_ST_fsm_state183 = 214'd6129982163463555433433388108601236734474956488734408704;
parameter    ap_ST_fsm_state184 = 214'd12259964326927110866866776217202473468949912977468817408;
parameter    ap_ST_fsm_state185 = 214'd24519928653854221733733552434404946937899825954937634816;
parameter    ap_ST_fsm_state186 = 214'd49039857307708443467467104868809893875799651909875269632;
parameter    ap_ST_fsm_state187 = 214'd98079714615416886934934209737619787751599303819750539264;
parameter    ap_ST_fsm_state188 = 214'd196159429230833773869868419475239575503198607639501078528;
parameter    ap_ST_fsm_state189 = 214'd392318858461667547739736838950479151006397215279002157056;
parameter    ap_ST_fsm_state190 = 214'd784637716923335095479473677900958302012794430558004314112;
parameter    ap_ST_fsm_state191 = 214'd1569275433846670190958947355801916604025588861116008628224;
parameter    ap_ST_fsm_state192 = 214'd3138550867693340381917894711603833208051177722232017256448;
parameter    ap_ST_fsm_state193 = 214'd6277101735386680763835789423207666416102355444464034512896;
parameter    ap_ST_fsm_state194 = 214'd12554203470773361527671578846415332832204710888928069025792;
parameter    ap_ST_fsm_state195 = 214'd25108406941546723055343157692830665664409421777856138051584;
parameter    ap_ST_fsm_state196 = 214'd50216813883093446110686315385661331328818843555712276103168;
parameter    ap_ST_fsm_state197 = 214'd100433627766186892221372630771322662657637687111424552206336;
parameter    ap_ST_fsm_state198 = 214'd200867255532373784442745261542645325315275374222849104412672;
parameter    ap_ST_fsm_state199 = 214'd401734511064747568885490523085290650630550748445698208825344;
parameter    ap_ST_fsm_state200 = 214'd803469022129495137770981046170581301261101496891396417650688;
parameter    ap_ST_fsm_state201 = 214'd1606938044258990275541962092341162602522202993782792835301376;
parameter    ap_ST_fsm_state202 = 214'd3213876088517980551083924184682325205044405987565585670602752;
parameter    ap_ST_fsm_state203 = 214'd6427752177035961102167848369364650410088811975131171341205504;
parameter    ap_ST_fsm_state204 = 214'd12855504354071922204335696738729300820177623950262342682411008;
parameter    ap_ST_fsm_state205 = 214'd25711008708143844408671393477458601640355247900524685364822016;
parameter    ap_ST_fsm_state206 = 214'd51422017416287688817342786954917203280710495801049370729644032;
parameter    ap_ST_fsm_state207 = 214'd102844034832575377634685573909834406561420991602098741459288064;
parameter    ap_ST_fsm_state208 = 214'd205688069665150755269371147819668813122841983204197482918576128;
parameter    ap_ST_fsm_state209 = 214'd411376139330301510538742295639337626245683966408394965837152256;
parameter    ap_ST_fsm_state210 = 214'd822752278660603021077484591278675252491367932816789931674304512;
parameter    ap_ST_fsm_state211 = 214'd1645504557321206042154969182557350504982735865633579863348609024;
parameter    ap_ST_fsm_state212 = 214'd3291009114642412084309938365114701009965471731267159726697218048;
parameter    ap_ST_fsm_state213 = 214'd6582018229284824168619876730229402019930943462534319453394436096;
parameter    ap_ST_fsm_state214 = 214'd13164036458569648337239753460458804039861886925068638906788872192;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_USER_VALUE = 0;
parameter    C_M_AXI_GMEM_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
output   m_axi_gmem_AWVALID;
input   m_axi_gmem_AWREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1:0] m_axi_gmem_AWADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_AWID;
output  [7:0] m_axi_gmem_AWLEN;
output  [2:0] m_axi_gmem_AWSIZE;
output  [1:0] m_axi_gmem_AWBURST;
output  [1:0] m_axi_gmem_AWLOCK;
output  [3:0] m_axi_gmem_AWCACHE;
output  [2:0] m_axi_gmem_AWPROT;
output  [3:0] m_axi_gmem_AWQOS;
output  [3:0] m_axi_gmem_AWREGION;
output  [C_M_AXI_GMEM_AWUSER_WIDTH - 1:0] m_axi_gmem_AWUSER;
output   m_axi_gmem_WVALID;
input   m_axi_gmem_WREADY;
output  [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem_WDATA;
output  [C_M_AXI_GMEM_WSTRB_WIDTH - 1:0] m_axi_gmem_WSTRB;
output   m_axi_gmem_WLAST;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_WID;
output  [C_M_AXI_GMEM_WUSER_WIDTH - 1:0] m_axi_gmem_WUSER;
output   m_axi_gmem_ARVALID;
input   m_axi_gmem_ARREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1:0] m_axi_gmem_ARADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_ARID;
output  [7:0] m_axi_gmem_ARLEN;
output  [2:0] m_axi_gmem_ARSIZE;
output  [1:0] m_axi_gmem_ARBURST;
output  [1:0] m_axi_gmem_ARLOCK;
output  [3:0] m_axi_gmem_ARCACHE;
output  [2:0] m_axi_gmem_ARPROT;
output  [3:0] m_axi_gmem_ARQOS;
output  [3:0] m_axi_gmem_ARREGION;
output  [C_M_AXI_GMEM_ARUSER_WIDTH - 1:0] m_axi_gmem_ARUSER;
input   m_axi_gmem_RVALID;
output   m_axi_gmem_RREADY;
input  [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem_RDATA;
input   m_axi_gmem_RLAST;
input  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_RID;
input  [C_M_AXI_GMEM_RUSER_WIDTH - 1:0] m_axi_gmem_RUSER;
input  [1:0] m_axi_gmem_RRESP;
input   m_axi_gmem_BVALID;
output   m_axi_gmem_BREADY;
input  [1:0] m_axi_gmem_BRESP;
input  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_BID;
input  [C_M_AXI_GMEM_BUSER_WIDTH - 1:0] m_axi_gmem_BUSER;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

(* shreg_extract = "no" *) reg    ap_rst_reg_2;
(* shreg_extract = "no" *) reg    ap_rst_reg_1;
(* shreg_extract = "no" *) reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
wire    ap_continue;
reg    ap_done_reg;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [213:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [63:0] in1;
wire   [63:0] in2;
wire   [63:0] out_r;
wire   [31:0] size;
reg    gmem_blk_n_AR;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state75;
reg    gmem_blk_n_AW;
wire    ap_CS_fsm_state144;
reg    gmem_blk_n_B;
wire    ap_CS_fsm_state214;
reg   [0:0] icmp_ln83_reg_443;
wire   [0:0] icmp_ln76_fu_174_p2;
reg   [0:0] icmp_ln76_reg_399;
wire   [23:0] add_ln76_1_fu_204_p2;
reg   [23:0] add_ln76_1_reg_417;
wire   [23:0] add_ln76_2_fu_228_p2;
reg   [23:0] add_ln76_2_reg_425;
wire    ap_CS_fsm_state2;
wire   [31:0] add_ln80_3_fu_268_p2;
reg   [31:0] add_ln80_3_reg_430;
wire   [0:0] icmp_ln76_1_fu_223_p2;
wire   [31:0] chunk_size_fu_292_p3;
reg   [31:0] chunk_size_reg_435;
wire   [0:0] icmp_ln83_fu_300_p2;
reg   [61:0] trunc_ln2_reg_447;
reg   [61:0] trunc_ln3_reg_453;
reg   [61:0] trunc_ln90_1_reg_459;
wire   [30:0] trunc_ln83_fu_346_p1;
reg   [30:0] trunc_ln83_reg_470;
wire    ap_CS_fsm_state73;
reg   [7:0] v1_buffer_address0;
reg    v1_buffer_ce0;
reg    v1_buffer_we0;
wire   [31:0] v1_buffer_q0;
wire    grp_krnl_vadd_Pipeline_read1_fu_155_ap_start;
wire    grp_krnl_vadd_Pipeline_read1_fu_155_ap_done;
wire    grp_krnl_vadd_Pipeline_read1_fu_155_ap_idle;
wire    grp_krnl_vadd_Pipeline_read1_fu_155_ap_ready;
wire    grp_krnl_vadd_Pipeline_read1_fu_155_m_axi_gmem_AWVALID;
wire   [63:0] grp_krnl_vadd_Pipeline_read1_fu_155_m_axi_gmem_AWADDR;
wire   [0:0] grp_krnl_vadd_Pipeline_read1_fu_155_m_axi_gmem_AWID;
wire   [31:0] grp_krnl_vadd_Pipeline_read1_fu_155_m_axi_gmem_AWLEN;
wire   [2:0] grp_krnl_vadd_Pipeline_read1_fu_155_m_axi_gmem_AWSIZE;
wire   [1:0] grp_krnl_vadd_Pipeline_read1_fu_155_m_axi_gmem_AWBURST;
wire   [1:0] grp_krnl_vadd_Pipeline_read1_fu_155_m_axi_gmem_AWLOCK;
wire   [3:0] grp_krnl_vadd_Pipeline_read1_fu_155_m_axi_gmem_AWCACHE;
wire   [2:0] grp_krnl_vadd_Pipeline_read1_fu_155_m_axi_gmem_AWPROT;
wire   [3:0] grp_krnl_vadd_Pipeline_read1_fu_155_m_axi_gmem_AWQOS;
wire   [3:0] grp_krnl_vadd_Pipeline_read1_fu_155_m_axi_gmem_AWREGION;
wire   [0:0] grp_krnl_vadd_Pipeline_read1_fu_155_m_axi_gmem_AWUSER;
wire    grp_krnl_vadd_Pipeline_read1_fu_155_m_axi_gmem_WVALID;
wire   [31:0] grp_krnl_vadd_Pipeline_read1_fu_155_m_axi_gmem_WDATA;
wire   [3:0] grp_krnl_vadd_Pipeline_read1_fu_155_m_axi_gmem_WSTRB;
wire    grp_krnl_vadd_Pipeline_read1_fu_155_m_axi_gmem_WLAST;
wire   [0:0] grp_krnl_vadd_Pipeline_read1_fu_155_m_axi_gmem_WID;
wire   [0:0] grp_krnl_vadd_Pipeline_read1_fu_155_m_axi_gmem_WUSER;
wire    grp_krnl_vadd_Pipeline_read1_fu_155_m_axi_gmem_ARVALID;
wire   [63:0] grp_krnl_vadd_Pipeline_read1_fu_155_m_axi_gmem_ARADDR;
wire   [0:0] grp_krnl_vadd_Pipeline_read1_fu_155_m_axi_gmem_ARID;
wire   [31:0] grp_krnl_vadd_Pipeline_read1_fu_155_m_axi_gmem_ARLEN;
wire   [2:0] grp_krnl_vadd_Pipeline_read1_fu_155_m_axi_gmem_ARSIZE;
wire   [1:0] grp_krnl_vadd_Pipeline_read1_fu_155_m_axi_gmem_ARBURST;
wire   [1:0] grp_krnl_vadd_Pipeline_read1_fu_155_m_axi_gmem_ARLOCK;
wire   [3:0] grp_krnl_vadd_Pipeline_read1_fu_155_m_axi_gmem_ARCACHE;
wire   [2:0] grp_krnl_vadd_Pipeline_read1_fu_155_m_axi_gmem_ARPROT;
wire   [3:0] grp_krnl_vadd_Pipeline_read1_fu_155_m_axi_gmem_ARQOS;
wire   [3:0] grp_krnl_vadd_Pipeline_read1_fu_155_m_axi_gmem_ARREGION;
wire   [0:0] grp_krnl_vadd_Pipeline_read1_fu_155_m_axi_gmem_ARUSER;
wire    grp_krnl_vadd_Pipeline_read1_fu_155_m_axi_gmem_RREADY;
wire    grp_krnl_vadd_Pipeline_read1_fu_155_m_axi_gmem_BREADY;
wire   [7:0] grp_krnl_vadd_Pipeline_read1_fu_155_v1_buffer_address0;
wire    grp_krnl_vadd_Pipeline_read1_fu_155_v1_buffer_ce0;
wire    grp_krnl_vadd_Pipeline_read1_fu_155_v1_buffer_we0;
wire   [31:0] grp_krnl_vadd_Pipeline_read1_fu_155_v1_buffer_d0;
wire    grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_ap_start;
wire    grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_ap_done;
wire    grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_ap_idle;
wire    grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_ap_ready;
wire    grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_m_axi_gmem_AWVALID;
wire   [63:0] grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_m_axi_gmem_AWADDR;
wire   [0:0] grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_m_axi_gmem_AWID;
wire   [31:0] grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_m_axi_gmem_AWLEN;
wire   [2:0] grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_m_axi_gmem_AWSIZE;
wire   [1:0] grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_m_axi_gmem_AWBURST;
wire   [1:0] grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_m_axi_gmem_AWLOCK;
wire   [3:0] grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_m_axi_gmem_AWCACHE;
wire   [2:0] grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_m_axi_gmem_AWPROT;
wire   [3:0] grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_m_axi_gmem_AWQOS;
wire   [3:0] grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_m_axi_gmem_AWREGION;
wire   [0:0] grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_m_axi_gmem_AWUSER;
wire    grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_m_axi_gmem_WVALID;
wire   [31:0] grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_m_axi_gmem_WDATA;
wire   [3:0] grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_m_axi_gmem_WSTRB;
wire    grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_m_axi_gmem_WLAST;
wire   [0:0] grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_m_axi_gmem_WID;
wire   [0:0] grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_m_axi_gmem_WUSER;
wire    grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_m_axi_gmem_ARVALID;
wire   [63:0] grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_m_axi_gmem_ARADDR;
wire   [0:0] grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_m_axi_gmem_ARID;
wire   [31:0] grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_m_axi_gmem_ARLEN;
wire   [2:0] grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_m_axi_gmem_ARSIZE;
wire   [1:0] grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_m_axi_gmem_ARBURST;
wire   [1:0] grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_m_axi_gmem_ARLOCK;
wire   [3:0] grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_m_axi_gmem_ARCACHE;
wire   [2:0] grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_m_axi_gmem_ARPROT;
wire   [3:0] grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_m_axi_gmem_ARQOS;
wire   [3:0] grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_m_axi_gmem_ARREGION;
wire   [0:0] grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_m_axi_gmem_ARUSER;
wire    grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_m_axi_gmem_RREADY;
wire    grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_m_axi_gmem_BREADY;
wire   [7:0] grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_v1_buffer_address0;
wire    grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_v1_buffer_ce0;
reg    gmem_AWVALID;
wire    gmem_AWREADY;
reg   [63:0] gmem_AWADDR;
reg   [0:0] gmem_AWID;
reg   [31:0] gmem_AWLEN;
reg   [2:0] gmem_AWSIZE;
reg   [1:0] gmem_AWBURST;
reg   [1:0] gmem_AWLOCK;
reg   [3:0] gmem_AWCACHE;
reg   [2:0] gmem_AWPROT;
reg   [3:0] gmem_AWQOS;
reg   [3:0] gmem_AWREGION;
reg   [0:0] gmem_AWUSER;
reg    gmem_WVALID;
wire    gmem_WREADY;
reg    gmem_ARVALID;
wire    gmem_ARREADY;
reg   [63:0] gmem_ARADDR;
reg   [0:0] gmem_ARID;
reg   [31:0] gmem_ARLEN;
reg   [2:0] gmem_ARSIZE;
reg   [1:0] gmem_ARBURST;
reg   [1:0] gmem_ARLOCK;
reg   [3:0] gmem_ARCACHE;
reg   [2:0] gmem_ARPROT;
reg   [3:0] gmem_ARQOS;
reg   [3:0] gmem_ARREGION;
reg   [0:0] gmem_ARUSER;
wire    gmem_RVALID;
reg    gmem_RREADY;
wire   [31:0] gmem_RDATA;
wire    gmem_RLAST;
wire   [0:0] gmem_RID;
wire   [0:0] gmem_RUSER;
wire   [1:0] gmem_RRESP;
wire    gmem_BVALID;
reg    gmem_BREADY;
wire   [1:0] gmem_BRESP;
wire   [0:0] gmem_BID;
wire   [0:0] gmem_BUSER;
reg    grp_krnl_vadd_Pipeline_read1_fu_155_ap_start_reg;
wire    ap_CS_fsm_state74;
reg    grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_ap_start_reg;
wire    ap_CS_fsm_state145;
wire    ap_CS_fsm_state146;
wire  signed [63:0] sext_ln83_fu_336_p1;
wire  signed [63:0] sext_ln90_fu_350_p1;
wire  signed [63:0] sext_ln90_1_fu_360_p1;
reg    ap_block_state214;
reg   [31:0] i_fu_104;
reg    ap_block_state1;
reg   [23:0] indvar_fu_108;
wire   [30:0] trunc_ln76_fu_180_p1;
wire   [30:0] add_ln76_fu_184_p2;
wire   [22:0] trunc_ln76_1_fu_190_p4;
wire   [23:0] zext_ln76_fu_200_p1;
wire   [22:0] trunc_ln80_fu_237_p1;
wire   [32:0] shl_ln_fu_241_p3;
wire   [63:0] zext_ln80_fu_249_p1;
wire   [30:0] trunc_ln81_fu_279_p1;
wire   [31:0] zext_ln81_fu_283_p1;
wire   [0:0] icmp_ln80_fu_274_p2;
wire   [31:0] sub_ln80_fu_287_p2;
wire   [63:0] add_ln80_2_fu_263_p2;
wire   [63:0] add_ln80_fu_253_p2;
wire   [63:0] add_ln80_1_fu_258_p2;
reg   [213:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
wire    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
wire    ap_ST_fsm_state24_blk;
wire    ap_ST_fsm_state25_blk;
wire    ap_ST_fsm_state26_blk;
wire    ap_ST_fsm_state27_blk;
wire    ap_ST_fsm_state28_blk;
wire    ap_ST_fsm_state29_blk;
wire    ap_ST_fsm_state30_blk;
wire    ap_ST_fsm_state31_blk;
wire    ap_ST_fsm_state32_blk;
wire    ap_ST_fsm_state33_blk;
wire    ap_ST_fsm_state34_blk;
wire    ap_ST_fsm_state35_blk;
wire    ap_ST_fsm_state36_blk;
wire    ap_ST_fsm_state37_blk;
wire    ap_ST_fsm_state38_blk;
wire    ap_ST_fsm_state39_blk;
wire    ap_ST_fsm_state40_blk;
wire    ap_ST_fsm_state41_blk;
wire    ap_ST_fsm_state42_blk;
wire    ap_ST_fsm_state43_blk;
wire    ap_ST_fsm_state44_blk;
wire    ap_ST_fsm_state45_blk;
wire    ap_ST_fsm_state46_blk;
wire    ap_ST_fsm_state47_blk;
wire    ap_ST_fsm_state48_blk;
wire    ap_ST_fsm_state49_blk;
wire    ap_ST_fsm_state50_blk;
wire    ap_ST_fsm_state51_blk;
wire    ap_ST_fsm_state52_blk;
wire    ap_ST_fsm_state53_blk;
wire    ap_ST_fsm_state54_blk;
wire    ap_ST_fsm_state55_blk;
wire    ap_ST_fsm_state56_blk;
wire    ap_ST_fsm_state57_blk;
wire    ap_ST_fsm_state58_blk;
wire    ap_ST_fsm_state59_blk;
wire    ap_ST_fsm_state60_blk;
wire    ap_ST_fsm_state61_blk;
wire    ap_ST_fsm_state62_blk;
wire    ap_ST_fsm_state63_blk;
wire    ap_ST_fsm_state64_blk;
wire    ap_ST_fsm_state65_blk;
wire    ap_ST_fsm_state66_blk;
wire    ap_ST_fsm_state67_blk;
wire    ap_ST_fsm_state68_blk;
wire    ap_ST_fsm_state69_blk;
wire    ap_ST_fsm_state70_blk;
wire    ap_ST_fsm_state71_blk;
wire    ap_ST_fsm_state72_blk;
wire    ap_ST_fsm_state73_blk;
reg    ap_ST_fsm_state74_blk;
reg    ap_ST_fsm_state75_blk;
wire    ap_ST_fsm_state76_blk;
wire    ap_ST_fsm_state77_blk;
wire    ap_ST_fsm_state78_blk;
wire    ap_ST_fsm_state79_blk;
wire    ap_ST_fsm_state80_blk;
wire    ap_ST_fsm_state81_blk;
wire    ap_ST_fsm_state82_blk;
wire    ap_ST_fsm_state83_blk;
wire    ap_ST_fsm_state84_blk;
wire    ap_ST_fsm_state85_blk;
wire    ap_ST_fsm_state86_blk;
wire    ap_ST_fsm_state87_blk;
wire    ap_ST_fsm_state88_blk;
wire    ap_ST_fsm_state89_blk;
wire    ap_ST_fsm_state90_blk;
wire    ap_ST_fsm_state91_blk;
wire    ap_ST_fsm_state92_blk;
wire    ap_ST_fsm_state93_blk;
wire    ap_ST_fsm_state94_blk;
wire    ap_ST_fsm_state95_blk;
wire    ap_ST_fsm_state96_blk;
wire    ap_ST_fsm_state97_blk;
wire    ap_ST_fsm_state98_blk;
wire    ap_ST_fsm_state99_blk;
wire    ap_ST_fsm_state100_blk;
wire    ap_ST_fsm_state101_blk;
wire    ap_ST_fsm_state102_blk;
wire    ap_ST_fsm_state103_blk;
wire    ap_ST_fsm_state104_blk;
wire    ap_ST_fsm_state105_blk;
wire    ap_ST_fsm_state106_blk;
wire    ap_ST_fsm_state107_blk;
wire    ap_ST_fsm_state108_blk;
wire    ap_ST_fsm_state109_blk;
wire    ap_ST_fsm_state110_blk;
wire    ap_ST_fsm_state111_blk;
wire    ap_ST_fsm_state112_blk;
wire    ap_ST_fsm_state113_blk;
wire    ap_ST_fsm_state114_blk;
wire    ap_ST_fsm_state115_blk;
wire    ap_ST_fsm_state116_blk;
wire    ap_ST_fsm_state117_blk;
wire    ap_ST_fsm_state118_blk;
wire    ap_ST_fsm_state119_blk;
wire    ap_ST_fsm_state120_blk;
wire    ap_ST_fsm_state121_blk;
wire    ap_ST_fsm_state122_blk;
wire    ap_ST_fsm_state123_blk;
wire    ap_ST_fsm_state124_blk;
wire    ap_ST_fsm_state125_blk;
wire    ap_ST_fsm_state126_blk;
wire    ap_ST_fsm_state127_blk;
wire    ap_ST_fsm_state128_blk;
wire    ap_ST_fsm_state129_blk;
wire    ap_ST_fsm_state130_blk;
wire    ap_ST_fsm_state131_blk;
wire    ap_ST_fsm_state132_blk;
wire    ap_ST_fsm_state133_blk;
wire    ap_ST_fsm_state134_blk;
wire    ap_ST_fsm_state135_blk;
wire    ap_ST_fsm_state136_blk;
wire    ap_ST_fsm_state137_blk;
wire    ap_ST_fsm_state138_blk;
wire    ap_ST_fsm_state139_blk;
wire    ap_ST_fsm_state140_blk;
wire    ap_ST_fsm_state141_blk;
wire    ap_ST_fsm_state142_blk;
wire    ap_ST_fsm_state143_blk;
reg    ap_ST_fsm_state144_blk;
wire    ap_ST_fsm_state145_blk;
reg    ap_ST_fsm_state146_blk;
wire    ap_ST_fsm_state147_blk;
wire    ap_ST_fsm_state148_blk;
wire    ap_ST_fsm_state149_blk;
wire    ap_ST_fsm_state150_blk;
wire    ap_ST_fsm_state151_blk;
wire    ap_ST_fsm_state152_blk;
wire    ap_ST_fsm_state153_blk;
wire    ap_ST_fsm_state154_blk;
wire    ap_ST_fsm_state155_blk;
wire    ap_ST_fsm_state156_blk;
wire    ap_ST_fsm_state157_blk;
wire    ap_ST_fsm_state158_blk;
wire    ap_ST_fsm_state159_blk;
wire    ap_ST_fsm_state160_blk;
wire    ap_ST_fsm_state161_blk;
wire    ap_ST_fsm_state162_blk;
wire    ap_ST_fsm_state163_blk;
wire    ap_ST_fsm_state164_blk;
wire    ap_ST_fsm_state165_blk;
wire    ap_ST_fsm_state166_blk;
wire    ap_ST_fsm_state167_blk;
wire    ap_ST_fsm_state168_blk;
wire    ap_ST_fsm_state169_blk;
wire    ap_ST_fsm_state170_blk;
wire    ap_ST_fsm_state171_blk;
wire    ap_ST_fsm_state172_blk;
wire    ap_ST_fsm_state173_blk;
wire    ap_ST_fsm_state174_blk;
wire    ap_ST_fsm_state175_blk;
wire    ap_ST_fsm_state176_blk;
wire    ap_ST_fsm_state177_blk;
wire    ap_ST_fsm_state178_blk;
wire    ap_ST_fsm_state179_blk;
wire    ap_ST_fsm_state180_blk;
wire    ap_ST_fsm_state181_blk;
wire    ap_ST_fsm_state182_blk;
wire    ap_ST_fsm_state183_blk;
wire    ap_ST_fsm_state184_blk;
wire    ap_ST_fsm_state185_blk;
wire    ap_ST_fsm_state186_blk;
wire    ap_ST_fsm_state187_blk;
wire    ap_ST_fsm_state188_blk;
wire    ap_ST_fsm_state189_blk;
wire    ap_ST_fsm_state190_blk;
wire    ap_ST_fsm_state191_blk;
wire    ap_ST_fsm_state192_blk;
wire    ap_ST_fsm_state193_blk;
wire    ap_ST_fsm_state194_blk;
wire    ap_ST_fsm_state195_blk;
wire    ap_ST_fsm_state196_blk;
wire    ap_ST_fsm_state197_blk;
wire    ap_ST_fsm_state198_blk;
wire    ap_ST_fsm_state199_blk;
wire    ap_ST_fsm_state200_blk;
wire    ap_ST_fsm_state201_blk;
wire    ap_ST_fsm_state202_blk;
wire    ap_ST_fsm_state203_blk;
wire    ap_ST_fsm_state204_blk;
wire    ap_ST_fsm_state205_blk;
wire    ap_ST_fsm_state206_blk;
wire    ap_ST_fsm_state207_blk;
wire    ap_ST_fsm_state208_blk;
wire    ap_ST_fsm_state209_blk;
wire    ap_ST_fsm_state210_blk;
wire    ap_ST_fsm_state211_blk;
wire    ap_ST_fsm_state212_blk;
wire    ap_ST_fsm_state213_blk;
reg    ap_ST_fsm_state214_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_rst_reg_2 = 1'b1;
#0 ap_rst_reg_1 = 1'b1;
#0 ap_rst_n_inv = 1'b1;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 214'd1;
#0 grp_krnl_vadd_Pipeline_read1_fu_155_ap_start_reg = 1'b0;
#0 grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_ap_start_reg = 1'b0;
end

krnl_vadd_v1_buffer #(
    .DataWidth( 32 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
v1_buffer_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(v1_buffer_address0),
    .ce0(v1_buffer_ce0),
    .we0(v1_buffer_we0),
    .d0(grp_krnl_vadd_Pipeline_read1_fu_155_v1_buffer_d0),
    .q0(v1_buffer_q0)
);

krnl_vadd_krnl_vadd_Pipeline_read1 grp_krnl_vadd_Pipeline_read1_fu_155(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_krnl_vadd_Pipeline_read1_fu_155_ap_start),
    .ap_done(grp_krnl_vadd_Pipeline_read1_fu_155_ap_done),
    .ap_idle(grp_krnl_vadd_Pipeline_read1_fu_155_ap_idle),
    .ap_ready(grp_krnl_vadd_Pipeline_read1_fu_155_ap_ready),
    .m_axi_gmem_AWVALID(grp_krnl_vadd_Pipeline_read1_fu_155_m_axi_gmem_AWVALID),
    .m_axi_gmem_AWREADY(1'b0),
    .m_axi_gmem_AWADDR(grp_krnl_vadd_Pipeline_read1_fu_155_m_axi_gmem_AWADDR),
    .m_axi_gmem_AWID(grp_krnl_vadd_Pipeline_read1_fu_155_m_axi_gmem_AWID),
    .m_axi_gmem_AWLEN(grp_krnl_vadd_Pipeline_read1_fu_155_m_axi_gmem_AWLEN),
    .m_axi_gmem_AWSIZE(grp_krnl_vadd_Pipeline_read1_fu_155_m_axi_gmem_AWSIZE),
    .m_axi_gmem_AWBURST(grp_krnl_vadd_Pipeline_read1_fu_155_m_axi_gmem_AWBURST),
    .m_axi_gmem_AWLOCK(grp_krnl_vadd_Pipeline_read1_fu_155_m_axi_gmem_AWLOCK),
    .m_axi_gmem_AWCACHE(grp_krnl_vadd_Pipeline_read1_fu_155_m_axi_gmem_AWCACHE),
    .m_axi_gmem_AWPROT(grp_krnl_vadd_Pipeline_read1_fu_155_m_axi_gmem_AWPROT),
    .m_axi_gmem_AWQOS(grp_krnl_vadd_Pipeline_read1_fu_155_m_axi_gmem_AWQOS),
    .m_axi_gmem_AWREGION(grp_krnl_vadd_Pipeline_read1_fu_155_m_axi_gmem_AWREGION),
    .m_axi_gmem_AWUSER(grp_krnl_vadd_Pipeline_read1_fu_155_m_axi_gmem_AWUSER),
    .m_axi_gmem_WVALID(grp_krnl_vadd_Pipeline_read1_fu_155_m_axi_gmem_WVALID),
    .m_axi_gmem_WREADY(1'b0),
    .m_axi_gmem_WDATA(grp_krnl_vadd_Pipeline_read1_fu_155_m_axi_gmem_WDATA),
    .m_axi_gmem_WSTRB(grp_krnl_vadd_Pipeline_read1_fu_155_m_axi_gmem_WSTRB),
    .m_axi_gmem_WLAST(grp_krnl_vadd_Pipeline_read1_fu_155_m_axi_gmem_WLAST),
    .m_axi_gmem_WID(grp_krnl_vadd_Pipeline_read1_fu_155_m_axi_gmem_WID),
    .m_axi_gmem_WUSER(grp_krnl_vadd_Pipeline_read1_fu_155_m_axi_gmem_WUSER),
    .m_axi_gmem_ARVALID(grp_krnl_vadd_Pipeline_read1_fu_155_m_axi_gmem_ARVALID),
    .m_axi_gmem_ARREADY(gmem_ARREADY),
    .m_axi_gmem_ARADDR(grp_krnl_vadd_Pipeline_read1_fu_155_m_axi_gmem_ARADDR),
    .m_axi_gmem_ARID(grp_krnl_vadd_Pipeline_read1_fu_155_m_axi_gmem_ARID),
    .m_axi_gmem_ARLEN(grp_krnl_vadd_Pipeline_read1_fu_155_m_axi_gmem_ARLEN),
    .m_axi_gmem_ARSIZE(grp_krnl_vadd_Pipeline_read1_fu_155_m_axi_gmem_ARSIZE),
    .m_axi_gmem_ARBURST(grp_krnl_vadd_Pipeline_read1_fu_155_m_axi_gmem_ARBURST),
    .m_axi_gmem_ARLOCK(grp_krnl_vadd_Pipeline_read1_fu_155_m_axi_gmem_ARLOCK),
    .m_axi_gmem_ARCACHE(grp_krnl_vadd_Pipeline_read1_fu_155_m_axi_gmem_ARCACHE),
    .m_axi_gmem_ARPROT(grp_krnl_vadd_Pipeline_read1_fu_155_m_axi_gmem_ARPROT),
    .m_axi_gmem_ARQOS(grp_krnl_vadd_Pipeline_read1_fu_155_m_axi_gmem_ARQOS),
    .m_axi_gmem_ARREGION(grp_krnl_vadd_Pipeline_read1_fu_155_m_axi_gmem_ARREGION),
    .m_axi_gmem_ARUSER(grp_krnl_vadd_Pipeline_read1_fu_155_m_axi_gmem_ARUSER),
    .m_axi_gmem_RVALID(gmem_RVALID),
    .m_axi_gmem_RREADY(grp_krnl_vadd_Pipeline_read1_fu_155_m_axi_gmem_RREADY),
    .m_axi_gmem_RDATA(gmem_RDATA),
    .m_axi_gmem_RLAST(gmem_RLAST),
    .m_axi_gmem_RID(gmem_RID),
    .m_axi_gmem_RUSER(gmem_RUSER),
    .m_axi_gmem_RRESP(gmem_RRESP),
    .m_axi_gmem_BVALID(1'b0),
    .m_axi_gmem_BREADY(grp_krnl_vadd_Pipeline_read1_fu_155_m_axi_gmem_BREADY),
    .m_axi_gmem_BRESP(2'd0),
    .m_axi_gmem_BID(1'd0),
    .m_axi_gmem_BUSER(1'd0),
    .sext_ln83(trunc_ln2_reg_447),
    .trunc_ln83_1(trunc_ln83_reg_470),
    .v1_buffer_address0(grp_krnl_vadd_Pipeline_read1_fu_155_v1_buffer_address0),
    .v1_buffer_ce0(grp_krnl_vadd_Pipeline_read1_fu_155_v1_buffer_ce0),
    .v1_buffer_we0(grp_krnl_vadd_Pipeline_read1_fu_155_v1_buffer_we0),
    .v1_buffer_d0(grp_krnl_vadd_Pipeline_read1_fu_155_v1_buffer_d0)
);

krnl_vadd_krnl_vadd_Pipeline_vadd_writeC grp_krnl_vadd_Pipeline_vadd_writeC_fu_164(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_ap_start),
    .ap_done(grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_ap_done),
    .ap_idle(grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_ap_idle),
    .ap_ready(grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_ap_ready),
    .m_axi_gmem_AWVALID(grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_m_axi_gmem_AWVALID),
    .m_axi_gmem_AWREADY(gmem_AWREADY),
    .m_axi_gmem_AWADDR(grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_m_axi_gmem_AWADDR),
    .m_axi_gmem_AWID(grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_m_axi_gmem_AWID),
    .m_axi_gmem_AWLEN(grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_m_axi_gmem_AWLEN),
    .m_axi_gmem_AWSIZE(grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_m_axi_gmem_AWSIZE),
    .m_axi_gmem_AWBURST(grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_m_axi_gmem_AWBURST),
    .m_axi_gmem_AWLOCK(grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_m_axi_gmem_AWLOCK),
    .m_axi_gmem_AWCACHE(grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_m_axi_gmem_AWCACHE),
    .m_axi_gmem_AWPROT(grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_m_axi_gmem_AWPROT),
    .m_axi_gmem_AWQOS(grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_m_axi_gmem_AWQOS),
    .m_axi_gmem_AWREGION(grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_m_axi_gmem_AWREGION),
    .m_axi_gmem_AWUSER(grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_m_axi_gmem_AWUSER),
    .m_axi_gmem_WVALID(grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_m_axi_gmem_WVALID),
    .m_axi_gmem_WREADY(gmem_WREADY),
    .m_axi_gmem_WDATA(grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_m_axi_gmem_WDATA),
    .m_axi_gmem_WSTRB(grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_m_axi_gmem_WSTRB),
    .m_axi_gmem_WLAST(grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_m_axi_gmem_WLAST),
    .m_axi_gmem_WID(grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_m_axi_gmem_WID),
    .m_axi_gmem_WUSER(grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_m_axi_gmem_WUSER),
    .m_axi_gmem_ARVALID(grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_m_axi_gmem_ARVALID),
    .m_axi_gmem_ARREADY(gmem_ARREADY),
    .m_axi_gmem_ARADDR(grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_m_axi_gmem_ARADDR),
    .m_axi_gmem_ARID(grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_m_axi_gmem_ARID),
    .m_axi_gmem_ARLEN(grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_m_axi_gmem_ARLEN),
    .m_axi_gmem_ARSIZE(grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_m_axi_gmem_ARSIZE),
    .m_axi_gmem_ARBURST(grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_m_axi_gmem_ARBURST),
    .m_axi_gmem_ARLOCK(grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_m_axi_gmem_ARLOCK),
    .m_axi_gmem_ARCACHE(grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_m_axi_gmem_ARCACHE),
    .m_axi_gmem_ARPROT(grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_m_axi_gmem_ARPROT),
    .m_axi_gmem_ARQOS(grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_m_axi_gmem_ARQOS),
    .m_axi_gmem_ARREGION(grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_m_axi_gmem_ARREGION),
    .m_axi_gmem_ARUSER(grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_m_axi_gmem_ARUSER),
    .m_axi_gmem_RVALID(gmem_RVALID),
    .m_axi_gmem_RREADY(grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_m_axi_gmem_RREADY),
    .m_axi_gmem_RDATA(gmem_RDATA),
    .m_axi_gmem_RLAST(gmem_RLAST),
    .m_axi_gmem_RID(gmem_RID),
    .m_axi_gmem_RUSER(gmem_RUSER),
    .m_axi_gmem_RRESP(gmem_RRESP),
    .m_axi_gmem_BVALID(gmem_BVALID),
    .m_axi_gmem_BREADY(grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_m_axi_gmem_BREADY),
    .m_axi_gmem_BRESP(gmem_BRESP),
    .m_axi_gmem_BID(gmem_BID),
    .m_axi_gmem_BUSER(gmem_BUSER),
    .sext_ln90_1(trunc_ln90_1_reg_459),
    .sext_ln90(trunc_ln3_reg_453),
    .trunc_ln83_1(trunc_ln83_reg_470),
    .v1_buffer_address0(grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_v1_buffer_address0),
    .v1_buffer_ce0(grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_v1_buffer_ce0),
    .v1_buffer_q0(v1_buffer_q0)
);

krnl_vadd_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .in1(in1),
    .in2(in2),
    .out_r(out_r),
    .size(size),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_continue(ap_continue),
    .ap_idle(ap_idle)
);

krnl_vadd_gmem_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_DW( 32 ),
    .USER_AW( 64 ),
    .USER_MAXREQS( 69 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM_CACHE_VALUE ))
gmem_m_axi_U(
    .AWVALID(m_axi_gmem_AWVALID),
    .AWREADY(m_axi_gmem_AWREADY),
    .AWADDR(m_axi_gmem_AWADDR),
    .AWID(m_axi_gmem_AWID),
    .AWLEN(m_axi_gmem_AWLEN),
    .AWSIZE(m_axi_gmem_AWSIZE),
    .AWBURST(m_axi_gmem_AWBURST),
    .AWLOCK(m_axi_gmem_AWLOCK),
    .AWCACHE(m_axi_gmem_AWCACHE),
    .AWPROT(m_axi_gmem_AWPROT),
    .AWQOS(m_axi_gmem_AWQOS),
    .AWREGION(m_axi_gmem_AWREGION),
    .AWUSER(m_axi_gmem_AWUSER),
    .WVALID(m_axi_gmem_WVALID),
    .WREADY(m_axi_gmem_WREADY),
    .WDATA(m_axi_gmem_WDATA),
    .WSTRB(m_axi_gmem_WSTRB),
    .WLAST(m_axi_gmem_WLAST),
    .WID(m_axi_gmem_WID),
    .WUSER(m_axi_gmem_WUSER),
    .ARVALID(m_axi_gmem_ARVALID),
    .ARREADY(m_axi_gmem_ARREADY),
    .ARADDR(m_axi_gmem_ARADDR),
    .ARID(m_axi_gmem_ARID),
    .ARLEN(m_axi_gmem_ARLEN),
    .ARSIZE(m_axi_gmem_ARSIZE),
    .ARBURST(m_axi_gmem_ARBURST),
    .ARLOCK(m_axi_gmem_ARLOCK),
    .ARCACHE(m_axi_gmem_ARCACHE),
    .ARPROT(m_axi_gmem_ARPROT),
    .ARQOS(m_axi_gmem_ARQOS),
    .ARREGION(m_axi_gmem_ARREGION),
    .ARUSER(m_axi_gmem_ARUSER),
    .RVALID(m_axi_gmem_RVALID),
    .RREADY(m_axi_gmem_RREADY),
    .RDATA(m_axi_gmem_RDATA),
    .RLAST(m_axi_gmem_RLAST),
    .RID(m_axi_gmem_RID),
    .RUSER(m_axi_gmem_RUSER),
    .RRESP(m_axi_gmem_RRESP),
    .BVALID(m_axi_gmem_BVALID),
    .BREADY(m_axi_gmem_BREADY),
    .BRESP(m_axi_gmem_BRESP),
    .BID(m_axi_gmem_BID),
    .BUSER(m_axi_gmem_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(gmem_ARVALID),
    .I_ARREADY(gmem_ARREADY),
    .I_ARADDR(gmem_ARADDR),
    .I_ARID(gmem_ARID),
    .I_ARLEN(gmem_ARLEN),
    .I_ARSIZE(gmem_ARSIZE),
    .I_ARLOCK(gmem_ARLOCK),
    .I_ARCACHE(gmem_ARCACHE),
    .I_ARQOS(gmem_ARQOS),
    .I_ARPROT(gmem_ARPROT),
    .I_ARUSER(gmem_ARUSER),
    .I_ARBURST(gmem_ARBURST),
    .I_ARREGION(gmem_ARREGION),
    .I_RVALID(gmem_RVALID),
    .I_RREADY(gmem_RREADY),
    .I_RDATA(gmem_RDATA),
    .I_RID(gmem_RID),
    .I_RUSER(gmem_RUSER),
    .I_RRESP(gmem_RRESP),
    .I_RLAST(gmem_RLAST),
    .I_AWVALID(gmem_AWVALID),
    .I_AWREADY(gmem_AWREADY),
    .I_AWADDR(gmem_AWADDR),
    .I_AWID(gmem_AWID),
    .I_AWLEN(gmem_AWLEN),
    .I_AWSIZE(gmem_AWSIZE),
    .I_AWLOCK(gmem_AWLOCK),
    .I_AWCACHE(gmem_AWCACHE),
    .I_AWQOS(gmem_AWQOS),
    .I_AWPROT(gmem_AWPROT),
    .I_AWUSER(gmem_AWUSER),
    .I_AWBURST(gmem_AWBURST),
    .I_AWREGION(gmem_AWREGION),
    .I_WVALID(gmem_WVALID),
    .I_WREADY(gmem_WREADY),
    .I_WDATA(grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_m_axi_gmem_WDATA),
    .I_WID(grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_m_axi_gmem_WID),
    .I_WUSER(grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_m_axi_gmem_WUSER),
    .I_WLAST(grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_m_axi_gmem_WLAST),
    .I_WSTRB(grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_m_axi_gmem_WSTRB),
    .I_BVALID(gmem_BVALID),
    .I_BREADY(gmem_BREADY),
    .I_BRESP(gmem_BRESP),
    .I_BID(gmem_BID),
    .I_BUSER(gmem_BUSER)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state2) & ((icmp_ln76_1_fu_223_p2 == 1'd1) | (icmp_ln76_reg_399 == 1'd0)))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_krnl_vadd_Pipeline_read1_fu_155_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state73)) begin
            grp_krnl_vadd_Pipeline_read1_fu_155_ap_start_reg <= 1'b1;
        end else if ((grp_krnl_vadd_Pipeline_read1_fu_155_ap_ready == 1'b1)) begin
            grp_krnl_vadd_Pipeline_read1_fu_155_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state145)) begin
            grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_ap_start_reg <= 1'b1;
        end else if ((grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_ap_ready == 1'b1)) begin
            grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    ap_rst_n_inv <= ap_rst_reg_1;
end

always @ (posedge ap_clk) begin
    ap_rst_reg_1 <= ap_rst_reg_2;
end

always @ (posedge ap_clk) begin
    ap_rst_reg_2 <= ~ap_rst_n;
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (icmp_ln76_fu_174_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        i_fu_104 <= 32'd0;
    end else if ((~((gmem_BVALID == 1'b0) & (icmp_ln83_reg_443 == 1'd1)) & (1'b1 == ap_CS_fsm_state214))) begin
        i_fu_104 <= add_ln80_3_reg_430;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (icmp_ln76_fu_174_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        indvar_fu_108 <= 24'd0;
    end else if ((~((gmem_BVALID == 1'b0) & (icmp_ln83_reg_443 == 1'd1)) & (1'b1 == ap_CS_fsm_state214))) begin
        indvar_fu_108 <= add_ln76_2_reg_425;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln76_fu_174_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        add_ln76_1_reg_417 <= add_ln76_1_fu_204_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln76_reg_399 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        add_ln76_2_reg_425 <= add_ln76_2_fu_228_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln76_1_fu_223_p2 == 1'd0) & (icmp_ln76_reg_399 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        add_ln80_3_reg_430 <= add_ln80_3_fu_268_p2;
        chunk_size_reg_435 <= chunk_size_fu_292_p3;
        icmp_ln83_reg_443 <= icmp_ln83_fu_300_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        icmp_ln76_reg_399 <= icmp_ln76_fu_174_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln83_fu_300_p2 == 1'd1) & (icmp_ln76_1_fu_223_p2 == 1'd0) & (icmp_ln76_reg_399 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        trunc_ln2_reg_447 <= {{add_ln80_2_fu_263_p2[63:2]}};
        trunc_ln3_reg_453 <= {{add_ln80_fu_253_p2[63:2]}};
        trunc_ln90_1_reg_459 <= {{add_ln80_1_fu_258_p2[63:2]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state73)) begin
        trunc_ln83_reg_470 <= trunc_ln83_fu_346_p1;
    end
end

assign ap_ST_fsm_state100_blk = 1'b0;

assign ap_ST_fsm_state101_blk = 1'b0;

assign ap_ST_fsm_state102_blk = 1'b0;

assign ap_ST_fsm_state103_blk = 1'b0;

assign ap_ST_fsm_state104_blk = 1'b0;

assign ap_ST_fsm_state105_blk = 1'b0;

assign ap_ST_fsm_state106_blk = 1'b0;

assign ap_ST_fsm_state107_blk = 1'b0;

assign ap_ST_fsm_state108_blk = 1'b0;

assign ap_ST_fsm_state109_blk = 1'b0;

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state110_blk = 1'b0;

assign ap_ST_fsm_state111_blk = 1'b0;

assign ap_ST_fsm_state112_blk = 1'b0;

assign ap_ST_fsm_state113_blk = 1'b0;

assign ap_ST_fsm_state114_blk = 1'b0;

assign ap_ST_fsm_state115_blk = 1'b0;

assign ap_ST_fsm_state116_blk = 1'b0;

assign ap_ST_fsm_state117_blk = 1'b0;

assign ap_ST_fsm_state118_blk = 1'b0;

assign ap_ST_fsm_state119_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state120_blk = 1'b0;

assign ap_ST_fsm_state121_blk = 1'b0;

assign ap_ST_fsm_state122_blk = 1'b0;

assign ap_ST_fsm_state123_blk = 1'b0;

assign ap_ST_fsm_state124_blk = 1'b0;

assign ap_ST_fsm_state125_blk = 1'b0;

assign ap_ST_fsm_state126_blk = 1'b0;

assign ap_ST_fsm_state127_blk = 1'b0;

assign ap_ST_fsm_state128_blk = 1'b0;

assign ap_ST_fsm_state129_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

assign ap_ST_fsm_state130_blk = 1'b0;

assign ap_ST_fsm_state131_blk = 1'b0;

assign ap_ST_fsm_state132_blk = 1'b0;

assign ap_ST_fsm_state133_blk = 1'b0;

assign ap_ST_fsm_state134_blk = 1'b0;

assign ap_ST_fsm_state135_blk = 1'b0;

assign ap_ST_fsm_state136_blk = 1'b0;

assign ap_ST_fsm_state137_blk = 1'b0;

assign ap_ST_fsm_state138_blk = 1'b0;

assign ap_ST_fsm_state139_blk = 1'b0;

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state140_blk = 1'b0;

assign ap_ST_fsm_state141_blk = 1'b0;

assign ap_ST_fsm_state142_blk = 1'b0;

assign ap_ST_fsm_state143_blk = 1'b0;

always @ (*) begin
    if ((gmem_AWREADY == 1'b0)) begin
        ap_ST_fsm_state144_blk = 1'b1;
    end else begin
        ap_ST_fsm_state144_blk = 1'b0;
    end
end

assign ap_ST_fsm_state145_blk = 1'b0;

always @ (*) begin
    if ((grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_ap_done == 1'b0)) begin
        ap_ST_fsm_state146_blk = 1'b1;
    end else begin
        ap_ST_fsm_state146_blk = 1'b0;
    end
end

assign ap_ST_fsm_state147_blk = 1'b0;

assign ap_ST_fsm_state148_blk = 1'b0;

assign ap_ST_fsm_state149_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state150_blk = 1'b0;

assign ap_ST_fsm_state151_blk = 1'b0;

assign ap_ST_fsm_state152_blk = 1'b0;

assign ap_ST_fsm_state153_blk = 1'b0;

assign ap_ST_fsm_state154_blk = 1'b0;

assign ap_ST_fsm_state155_blk = 1'b0;

assign ap_ST_fsm_state156_blk = 1'b0;

assign ap_ST_fsm_state157_blk = 1'b0;

assign ap_ST_fsm_state158_blk = 1'b0;

assign ap_ST_fsm_state159_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state160_blk = 1'b0;

assign ap_ST_fsm_state161_blk = 1'b0;

assign ap_ST_fsm_state162_blk = 1'b0;

assign ap_ST_fsm_state163_blk = 1'b0;

assign ap_ST_fsm_state164_blk = 1'b0;

assign ap_ST_fsm_state165_blk = 1'b0;

assign ap_ST_fsm_state166_blk = 1'b0;

assign ap_ST_fsm_state167_blk = 1'b0;

assign ap_ST_fsm_state168_blk = 1'b0;

assign ap_ST_fsm_state169_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state170_blk = 1'b0;

assign ap_ST_fsm_state171_blk = 1'b0;

assign ap_ST_fsm_state172_blk = 1'b0;

assign ap_ST_fsm_state173_blk = 1'b0;

assign ap_ST_fsm_state174_blk = 1'b0;

assign ap_ST_fsm_state175_blk = 1'b0;

assign ap_ST_fsm_state176_blk = 1'b0;

assign ap_ST_fsm_state177_blk = 1'b0;

assign ap_ST_fsm_state178_blk = 1'b0;

assign ap_ST_fsm_state179_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state180_blk = 1'b0;

assign ap_ST_fsm_state181_blk = 1'b0;

assign ap_ST_fsm_state182_blk = 1'b0;

assign ap_ST_fsm_state183_blk = 1'b0;

assign ap_ST_fsm_state184_blk = 1'b0;

assign ap_ST_fsm_state185_blk = 1'b0;

assign ap_ST_fsm_state186_blk = 1'b0;

assign ap_ST_fsm_state187_blk = 1'b0;

assign ap_ST_fsm_state188_blk = 1'b0;

assign ap_ST_fsm_state189_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state190_blk = 1'b0;

assign ap_ST_fsm_state191_blk = 1'b0;

assign ap_ST_fsm_state192_blk = 1'b0;

assign ap_ST_fsm_state193_blk = 1'b0;

assign ap_ST_fsm_state194_blk = 1'b0;

assign ap_ST_fsm_state195_blk = 1'b0;

assign ap_ST_fsm_state196_blk = 1'b0;

assign ap_ST_fsm_state197_blk = 1'b0;

assign ap_ST_fsm_state198_blk = 1'b0;

assign ap_ST_fsm_state199_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if (((ap_done_reg == 1'b1) | (ap_start == 1'b0))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state200_blk = 1'b0;

assign ap_ST_fsm_state201_blk = 1'b0;

assign ap_ST_fsm_state202_blk = 1'b0;

assign ap_ST_fsm_state203_blk = 1'b0;

assign ap_ST_fsm_state204_blk = 1'b0;

assign ap_ST_fsm_state205_blk = 1'b0;

assign ap_ST_fsm_state206_blk = 1'b0;

assign ap_ST_fsm_state207_blk = 1'b0;

assign ap_ST_fsm_state208_blk = 1'b0;

assign ap_ST_fsm_state209_blk = 1'b0;

assign ap_ST_fsm_state20_blk = 1'b0;

assign ap_ST_fsm_state210_blk = 1'b0;

assign ap_ST_fsm_state211_blk = 1'b0;

assign ap_ST_fsm_state212_blk = 1'b0;

assign ap_ST_fsm_state213_blk = 1'b0;

always @ (*) begin
    if (((gmem_BVALID == 1'b0) & (icmp_ln83_reg_443 == 1'd1))) begin
        ap_ST_fsm_state214_blk = 1'b1;
    end else begin
        ap_ST_fsm_state214_blk = 1'b0;
    end
end

assign ap_ST_fsm_state21_blk = 1'b0;

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state23_blk = 1'b0;

assign ap_ST_fsm_state24_blk = 1'b0;

assign ap_ST_fsm_state25_blk = 1'b0;

assign ap_ST_fsm_state26_blk = 1'b0;

assign ap_ST_fsm_state27_blk = 1'b0;

assign ap_ST_fsm_state28_blk = 1'b0;

assign ap_ST_fsm_state29_blk = 1'b0;

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state30_blk = 1'b0;

assign ap_ST_fsm_state31_blk = 1'b0;

assign ap_ST_fsm_state32_blk = 1'b0;

assign ap_ST_fsm_state33_blk = 1'b0;

assign ap_ST_fsm_state34_blk = 1'b0;

assign ap_ST_fsm_state35_blk = 1'b0;

assign ap_ST_fsm_state36_blk = 1'b0;

assign ap_ST_fsm_state37_blk = 1'b0;

assign ap_ST_fsm_state38_blk = 1'b0;

assign ap_ST_fsm_state39_blk = 1'b0;

always @ (*) begin
    if ((gmem_ARREADY == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state40_blk = 1'b0;

assign ap_ST_fsm_state41_blk = 1'b0;

assign ap_ST_fsm_state42_blk = 1'b0;

assign ap_ST_fsm_state43_blk = 1'b0;

assign ap_ST_fsm_state44_blk = 1'b0;

assign ap_ST_fsm_state45_blk = 1'b0;

assign ap_ST_fsm_state46_blk = 1'b0;

assign ap_ST_fsm_state47_blk = 1'b0;

assign ap_ST_fsm_state48_blk = 1'b0;

assign ap_ST_fsm_state49_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state50_blk = 1'b0;

assign ap_ST_fsm_state51_blk = 1'b0;

assign ap_ST_fsm_state52_blk = 1'b0;

assign ap_ST_fsm_state53_blk = 1'b0;

assign ap_ST_fsm_state54_blk = 1'b0;

assign ap_ST_fsm_state55_blk = 1'b0;

assign ap_ST_fsm_state56_blk = 1'b0;

assign ap_ST_fsm_state57_blk = 1'b0;

assign ap_ST_fsm_state58_blk = 1'b0;

assign ap_ST_fsm_state59_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state60_blk = 1'b0;

assign ap_ST_fsm_state61_blk = 1'b0;

assign ap_ST_fsm_state62_blk = 1'b0;

assign ap_ST_fsm_state63_blk = 1'b0;

assign ap_ST_fsm_state64_blk = 1'b0;

assign ap_ST_fsm_state65_blk = 1'b0;

assign ap_ST_fsm_state66_blk = 1'b0;

assign ap_ST_fsm_state67_blk = 1'b0;

assign ap_ST_fsm_state68_blk = 1'b0;

assign ap_ST_fsm_state69_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state70_blk = 1'b0;

assign ap_ST_fsm_state71_blk = 1'b0;

assign ap_ST_fsm_state72_blk = 1'b0;

assign ap_ST_fsm_state73_blk = 1'b0;

always @ (*) begin
    if ((grp_krnl_vadd_Pipeline_read1_fu_155_ap_done == 1'b0)) begin
        ap_ST_fsm_state74_blk = 1'b1;
    end else begin
        ap_ST_fsm_state74_blk = 1'b0;
    end
end

always @ (*) begin
    if ((gmem_ARREADY == 1'b0)) begin
        ap_ST_fsm_state75_blk = 1'b1;
    end else begin
        ap_ST_fsm_state75_blk = 1'b0;
    end
end

assign ap_ST_fsm_state76_blk = 1'b0;

assign ap_ST_fsm_state77_blk = 1'b0;

assign ap_ST_fsm_state78_blk = 1'b0;

assign ap_ST_fsm_state79_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state80_blk = 1'b0;

assign ap_ST_fsm_state81_blk = 1'b0;

assign ap_ST_fsm_state82_blk = 1'b0;

assign ap_ST_fsm_state83_blk = 1'b0;

assign ap_ST_fsm_state84_blk = 1'b0;

assign ap_ST_fsm_state85_blk = 1'b0;

assign ap_ST_fsm_state86_blk = 1'b0;

assign ap_ST_fsm_state87_blk = 1'b0;

assign ap_ST_fsm_state88_blk = 1'b0;

assign ap_ST_fsm_state89_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state90_blk = 1'b0;

assign ap_ST_fsm_state91_blk = 1'b0;

assign ap_ST_fsm_state92_blk = 1'b0;

assign ap_ST_fsm_state93_blk = 1'b0;

assign ap_ST_fsm_state94_blk = 1'b0;

assign ap_ST_fsm_state95_blk = 1'b0;

assign ap_ST_fsm_state96_blk = 1'b0;

assign ap_ST_fsm_state97_blk = 1'b0;

assign ap_ST_fsm_state98_blk = 1'b0;

assign ap_ST_fsm_state99_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & ((icmp_ln76_1_fu_223_p2 == 1'd1) | (icmp_ln76_reg_399 == 1'd0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state2) & ((icmp_ln76_1_fu_223_p2 == 1'd1) | (icmp_ln76_reg_399 == 1'd0)))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((gmem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state75))) begin
        gmem_ARADDR = sext_ln90_fu_350_p1;
    end else if (((gmem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        gmem_ARADDR = sext_ln83_fu_336_p1;
    end else if (((1'b1 == ap_CS_fsm_state146) | (1'b1 == ap_CS_fsm_state145))) begin
        gmem_ARADDR = grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_m_axi_gmem_ARADDR;
    end else if (((1'b1 == ap_CS_fsm_state74) | (1'b1 == ap_CS_fsm_state73))) begin
        gmem_ARADDR = grp_krnl_vadd_Pipeline_read1_fu_155_m_axi_gmem_ARADDR;
    end else begin
        gmem_ARADDR = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state146) | (1'b1 == ap_CS_fsm_state145))) begin
        gmem_ARBURST = grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_m_axi_gmem_ARBURST;
    end else if (((1'b1 == ap_CS_fsm_state74) | (1'b1 == ap_CS_fsm_state73))) begin
        gmem_ARBURST = grp_krnl_vadd_Pipeline_read1_fu_155_m_axi_gmem_ARBURST;
    end else begin
        gmem_ARBURST = 2'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state146) | (1'b1 == ap_CS_fsm_state145))) begin
        gmem_ARCACHE = grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_m_axi_gmem_ARCACHE;
    end else if (((1'b1 == ap_CS_fsm_state74) | (1'b1 == ap_CS_fsm_state73))) begin
        gmem_ARCACHE = grp_krnl_vadd_Pipeline_read1_fu_155_m_axi_gmem_ARCACHE;
    end else begin
        gmem_ARCACHE = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state146) | (1'b1 == ap_CS_fsm_state145))) begin
        gmem_ARID = grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_m_axi_gmem_ARID;
    end else if (((1'b1 == ap_CS_fsm_state74) | (1'b1 == ap_CS_fsm_state73))) begin
        gmem_ARID = grp_krnl_vadd_Pipeline_read1_fu_155_m_axi_gmem_ARID;
    end else begin
        gmem_ARID = 1'd0;
    end
end

always @ (*) begin
    if ((((gmem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state75)) | ((gmem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state3)))) begin
        gmem_ARLEN = chunk_size_reg_435;
    end else if (((1'b1 == ap_CS_fsm_state146) | (1'b1 == ap_CS_fsm_state145))) begin
        gmem_ARLEN = grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_m_axi_gmem_ARLEN;
    end else if (((1'b1 == ap_CS_fsm_state74) | (1'b1 == ap_CS_fsm_state73))) begin
        gmem_ARLEN = grp_krnl_vadd_Pipeline_read1_fu_155_m_axi_gmem_ARLEN;
    end else begin
        gmem_ARLEN = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state146) | (1'b1 == ap_CS_fsm_state145))) begin
        gmem_ARLOCK = grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_m_axi_gmem_ARLOCK;
    end else if (((1'b1 == ap_CS_fsm_state74) | (1'b1 == ap_CS_fsm_state73))) begin
        gmem_ARLOCK = grp_krnl_vadd_Pipeline_read1_fu_155_m_axi_gmem_ARLOCK;
    end else begin
        gmem_ARLOCK = 2'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state146) | (1'b1 == ap_CS_fsm_state145))) begin
        gmem_ARPROT = grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_m_axi_gmem_ARPROT;
    end else if (((1'b1 == ap_CS_fsm_state74) | (1'b1 == ap_CS_fsm_state73))) begin
        gmem_ARPROT = grp_krnl_vadd_Pipeline_read1_fu_155_m_axi_gmem_ARPROT;
    end else begin
        gmem_ARPROT = 3'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state146) | (1'b1 == ap_CS_fsm_state145))) begin
        gmem_ARQOS = grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_m_axi_gmem_ARQOS;
    end else if (((1'b1 == ap_CS_fsm_state74) | (1'b1 == ap_CS_fsm_state73))) begin
        gmem_ARQOS = grp_krnl_vadd_Pipeline_read1_fu_155_m_axi_gmem_ARQOS;
    end else begin
        gmem_ARQOS = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state146) | (1'b1 == ap_CS_fsm_state145))) begin
        gmem_ARREGION = grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_m_axi_gmem_ARREGION;
    end else if (((1'b1 == ap_CS_fsm_state74) | (1'b1 == ap_CS_fsm_state73))) begin
        gmem_ARREGION = grp_krnl_vadd_Pipeline_read1_fu_155_m_axi_gmem_ARREGION;
    end else begin
        gmem_ARREGION = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state146) | (1'b1 == ap_CS_fsm_state145))) begin
        gmem_ARSIZE = grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_m_axi_gmem_ARSIZE;
    end else if (((1'b1 == ap_CS_fsm_state74) | (1'b1 == ap_CS_fsm_state73))) begin
        gmem_ARSIZE = grp_krnl_vadd_Pipeline_read1_fu_155_m_axi_gmem_ARSIZE;
    end else begin
        gmem_ARSIZE = 3'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state146) | (1'b1 == ap_CS_fsm_state145))) begin
        gmem_ARUSER = grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_m_axi_gmem_ARUSER;
    end else if (((1'b1 == ap_CS_fsm_state74) | (1'b1 == ap_CS_fsm_state73))) begin
        gmem_ARUSER = grp_krnl_vadd_Pipeline_read1_fu_155_m_axi_gmem_ARUSER;
    end else begin
        gmem_ARUSER = 1'd0;
    end
end

always @ (*) begin
    if ((((gmem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state75)) | ((gmem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state3)))) begin
        gmem_ARVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state146) | (1'b1 == ap_CS_fsm_state145))) begin
        gmem_ARVALID = grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_m_axi_gmem_ARVALID;
    end else if (((1'b1 == ap_CS_fsm_state74) | (1'b1 == ap_CS_fsm_state73))) begin
        gmem_ARVALID = grp_krnl_vadd_Pipeline_read1_fu_155_m_axi_gmem_ARVALID;
    end else begin
        gmem_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((gmem_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state144))) begin
        gmem_AWADDR = sext_ln90_1_fu_360_p1;
    end else if (((1'b1 == ap_CS_fsm_state146) | (1'b1 == ap_CS_fsm_state145))) begin
        gmem_AWADDR = grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_m_axi_gmem_AWADDR;
    end else begin
        gmem_AWADDR = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state146) | (1'b1 == ap_CS_fsm_state145))) begin
        gmem_AWBURST = grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_m_axi_gmem_AWBURST;
    end else begin
        gmem_AWBURST = 2'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state146) | (1'b1 == ap_CS_fsm_state145))) begin
        gmem_AWCACHE = grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_m_axi_gmem_AWCACHE;
    end else begin
        gmem_AWCACHE = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state146) | (1'b1 == ap_CS_fsm_state145))) begin
        gmem_AWID = grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_m_axi_gmem_AWID;
    end else begin
        gmem_AWID = 1'd0;
    end
end

always @ (*) begin
    if (((gmem_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state144))) begin
        gmem_AWLEN = chunk_size_reg_435;
    end else if (((1'b1 == ap_CS_fsm_state146) | (1'b1 == ap_CS_fsm_state145))) begin
        gmem_AWLEN = grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_m_axi_gmem_AWLEN;
    end else begin
        gmem_AWLEN = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state146) | (1'b1 == ap_CS_fsm_state145))) begin
        gmem_AWLOCK = grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_m_axi_gmem_AWLOCK;
    end else begin
        gmem_AWLOCK = 2'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state146) | (1'b1 == ap_CS_fsm_state145))) begin
        gmem_AWPROT = grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_m_axi_gmem_AWPROT;
    end else begin
        gmem_AWPROT = 3'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state146) | (1'b1 == ap_CS_fsm_state145))) begin
        gmem_AWQOS = grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_m_axi_gmem_AWQOS;
    end else begin
        gmem_AWQOS = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state146) | (1'b1 == ap_CS_fsm_state145))) begin
        gmem_AWREGION = grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_m_axi_gmem_AWREGION;
    end else begin
        gmem_AWREGION = 4'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state146) | (1'b1 == ap_CS_fsm_state145))) begin
        gmem_AWSIZE = grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_m_axi_gmem_AWSIZE;
    end else begin
        gmem_AWSIZE = 3'd0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state146) | (1'b1 == ap_CS_fsm_state145))) begin
        gmem_AWUSER = grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_m_axi_gmem_AWUSER;
    end else begin
        gmem_AWUSER = 1'd0;
    end
end

always @ (*) begin
    if (((gmem_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state144))) begin
        gmem_AWVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state146) | (1'b1 == ap_CS_fsm_state145))) begin
        gmem_AWVALID = grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_m_axi_gmem_AWVALID;
    end else begin
        gmem_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if ((~((gmem_BVALID == 1'b0) & (icmp_ln83_reg_443 == 1'd1)) & (icmp_ln83_reg_443 == 1'd1) & (1'b1 == ap_CS_fsm_state214))) begin
        gmem_BREADY = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state146) | (1'b1 == ap_CS_fsm_state145))) begin
        gmem_BREADY = grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_m_axi_gmem_BREADY;
    end else begin
        gmem_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state146) | (1'b1 == ap_CS_fsm_state145))) begin
        gmem_RREADY = grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_m_axi_gmem_RREADY;
    end else if (((1'b1 == ap_CS_fsm_state74) | (1'b1 == ap_CS_fsm_state73))) begin
        gmem_RREADY = grp_krnl_vadd_Pipeline_read1_fu_155_m_axi_gmem_RREADY;
    end else begin
        gmem_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state146) | (1'b1 == ap_CS_fsm_state145))) begin
        gmem_WVALID = grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_m_axi_gmem_WVALID;
    end else begin
        gmem_WVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state75) | (1'b1 == ap_CS_fsm_state3))) begin
        gmem_blk_n_AR = m_axi_gmem_ARREADY;
    end else begin
        gmem_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state144)) begin
        gmem_blk_n_AW = m_axi_gmem_AWREADY;
    end else begin
        gmem_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if (((icmp_ln83_reg_443 == 1'd1) & (1'b1 == ap_CS_fsm_state214))) begin
        gmem_blk_n_B = m_axi_gmem_BVALID;
    end else begin
        gmem_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state146)) begin
        v1_buffer_address0 = grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_v1_buffer_address0;
    end else if ((1'b1 == ap_CS_fsm_state74)) begin
        v1_buffer_address0 = grp_krnl_vadd_Pipeline_read1_fu_155_v1_buffer_address0;
    end else begin
        v1_buffer_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state146)) begin
        v1_buffer_ce0 = grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_v1_buffer_ce0;
    end else if ((1'b1 == ap_CS_fsm_state74)) begin
        v1_buffer_ce0 = grp_krnl_vadd_Pipeline_read1_fu_155_v1_buffer_ce0;
    end else begin
        v1_buffer_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state74)) begin
        v1_buffer_we0 = grp_krnl_vadd_Pipeline_read1_fu_155_v1_buffer_we0;
    end else begin
        v1_buffer_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_done_reg == 1'b1) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & ((icmp_ln76_1_fu_223_p2 == 1'd1) | (icmp_ln76_reg_399 == 1'd0)))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if (((icmp_ln83_fu_300_p2 == 1'd0) & (icmp_ln76_1_fu_223_p2 == 1'd0) & (icmp_ln76_reg_399 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state214;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((gmem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state35 : begin
            ap_NS_fsm = ap_ST_fsm_state36;
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state37;
        end
        ap_ST_fsm_state37 : begin
            ap_NS_fsm = ap_ST_fsm_state38;
        end
        ap_ST_fsm_state38 : begin
            ap_NS_fsm = ap_ST_fsm_state39;
        end
        ap_ST_fsm_state39 : begin
            ap_NS_fsm = ap_ST_fsm_state40;
        end
        ap_ST_fsm_state40 : begin
            ap_NS_fsm = ap_ST_fsm_state41;
        end
        ap_ST_fsm_state41 : begin
            ap_NS_fsm = ap_ST_fsm_state42;
        end
        ap_ST_fsm_state42 : begin
            ap_NS_fsm = ap_ST_fsm_state43;
        end
        ap_ST_fsm_state43 : begin
            ap_NS_fsm = ap_ST_fsm_state44;
        end
        ap_ST_fsm_state44 : begin
            ap_NS_fsm = ap_ST_fsm_state45;
        end
        ap_ST_fsm_state45 : begin
            ap_NS_fsm = ap_ST_fsm_state46;
        end
        ap_ST_fsm_state46 : begin
            ap_NS_fsm = ap_ST_fsm_state47;
        end
        ap_ST_fsm_state47 : begin
            ap_NS_fsm = ap_ST_fsm_state48;
        end
        ap_ST_fsm_state48 : begin
            ap_NS_fsm = ap_ST_fsm_state49;
        end
        ap_ST_fsm_state49 : begin
            ap_NS_fsm = ap_ST_fsm_state50;
        end
        ap_ST_fsm_state50 : begin
            ap_NS_fsm = ap_ST_fsm_state51;
        end
        ap_ST_fsm_state51 : begin
            ap_NS_fsm = ap_ST_fsm_state52;
        end
        ap_ST_fsm_state52 : begin
            ap_NS_fsm = ap_ST_fsm_state53;
        end
        ap_ST_fsm_state53 : begin
            ap_NS_fsm = ap_ST_fsm_state54;
        end
        ap_ST_fsm_state54 : begin
            ap_NS_fsm = ap_ST_fsm_state55;
        end
        ap_ST_fsm_state55 : begin
            ap_NS_fsm = ap_ST_fsm_state56;
        end
        ap_ST_fsm_state56 : begin
            ap_NS_fsm = ap_ST_fsm_state57;
        end
        ap_ST_fsm_state57 : begin
            ap_NS_fsm = ap_ST_fsm_state58;
        end
        ap_ST_fsm_state58 : begin
            ap_NS_fsm = ap_ST_fsm_state59;
        end
        ap_ST_fsm_state59 : begin
            ap_NS_fsm = ap_ST_fsm_state60;
        end
        ap_ST_fsm_state60 : begin
            ap_NS_fsm = ap_ST_fsm_state61;
        end
        ap_ST_fsm_state61 : begin
            ap_NS_fsm = ap_ST_fsm_state62;
        end
        ap_ST_fsm_state62 : begin
            ap_NS_fsm = ap_ST_fsm_state63;
        end
        ap_ST_fsm_state63 : begin
            ap_NS_fsm = ap_ST_fsm_state64;
        end
        ap_ST_fsm_state64 : begin
            ap_NS_fsm = ap_ST_fsm_state65;
        end
        ap_ST_fsm_state65 : begin
            ap_NS_fsm = ap_ST_fsm_state66;
        end
        ap_ST_fsm_state66 : begin
            ap_NS_fsm = ap_ST_fsm_state67;
        end
        ap_ST_fsm_state67 : begin
            ap_NS_fsm = ap_ST_fsm_state68;
        end
        ap_ST_fsm_state68 : begin
            ap_NS_fsm = ap_ST_fsm_state69;
        end
        ap_ST_fsm_state69 : begin
            ap_NS_fsm = ap_ST_fsm_state70;
        end
        ap_ST_fsm_state70 : begin
            ap_NS_fsm = ap_ST_fsm_state71;
        end
        ap_ST_fsm_state71 : begin
            ap_NS_fsm = ap_ST_fsm_state72;
        end
        ap_ST_fsm_state72 : begin
            ap_NS_fsm = ap_ST_fsm_state73;
        end
        ap_ST_fsm_state73 : begin
            ap_NS_fsm = ap_ST_fsm_state74;
        end
        ap_ST_fsm_state74 : begin
            if (((grp_krnl_vadd_Pipeline_read1_fu_155_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state74))) begin
                ap_NS_fsm = ap_ST_fsm_state75;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state74;
            end
        end
        ap_ST_fsm_state75 : begin
            if (((gmem_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state75))) begin
                ap_NS_fsm = ap_ST_fsm_state76;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state75;
            end
        end
        ap_ST_fsm_state76 : begin
            ap_NS_fsm = ap_ST_fsm_state77;
        end
        ap_ST_fsm_state77 : begin
            ap_NS_fsm = ap_ST_fsm_state78;
        end
        ap_ST_fsm_state78 : begin
            ap_NS_fsm = ap_ST_fsm_state79;
        end
        ap_ST_fsm_state79 : begin
            ap_NS_fsm = ap_ST_fsm_state80;
        end
        ap_ST_fsm_state80 : begin
            ap_NS_fsm = ap_ST_fsm_state81;
        end
        ap_ST_fsm_state81 : begin
            ap_NS_fsm = ap_ST_fsm_state82;
        end
        ap_ST_fsm_state82 : begin
            ap_NS_fsm = ap_ST_fsm_state83;
        end
        ap_ST_fsm_state83 : begin
            ap_NS_fsm = ap_ST_fsm_state84;
        end
        ap_ST_fsm_state84 : begin
            ap_NS_fsm = ap_ST_fsm_state85;
        end
        ap_ST_fsm_state85 : begin
            ap_NS_fsm = ap_ST_fsm_state86;
        end
        ap_ST_fsm_state86 : begin
            ap_NS_fsm = ap_ST_fsm_state87;
        end
        ap_ST_fsm_state87 : begin
            ap_NS_fsm = ap_ST_fsm_state88;
        end
        ap_ST_fsm_state88 : begin
            ap_NS_fsm = ap_ST_fsm_state89;
        end
        ap_ST_fsm_state89 : begin
            ap_NS_fsm = ap_ST_fsm_state90;
        end
        ap_ST_fsm_state90 : begin
            ap_NS_fsm = ap_ST_fsm_state91;
        end
        ap_ST_fsm_state91 : begin
            ap_NS_fsm = ap_ST_fsm_state92;
        end
        ap_ST_fsm_state92 : begin
            ap_NS_fsm = ap_ST_fsm_state93;
        end
        ap_ST_fsm_state93 : begin
            ap_NS_fsm = ap_ST_fsm_state94;
        end
        ap_ST_fsm_state94 : begin
            ap_NS_fsm = ap_ST_fsm_state95;
        end
        ap_ST_fsm_state95 : begin
            ap_NS_fsm = ap_ST_fsm_state96;
        end
        ap_ST_fsm_state96 : begin
            ap_NS_fsm = ap_ST_fsm_state97;
        end
        ap_ST_fsm_state97 : begin
            ap_NS_fsm = ap_ST_fsm_state98;
        end
        ap_ST_fsm_state98 : begin
            ap_NS_fsm = ap_ST_fsm_state99;
        end
        ap_ST_fsm_state99 : begin
            ap_NS_fsm = ap_ST_fsm_state100;
        end
        ap_ST_fsm_state100 : begin
            ap_NS_fsm = ap_ST_fsm_state101;
        end
        ap_ST_fsm_state101 : begin
            ap_NS_fsm = ap_ST_fsm_state102;
        end
        ap_ST_fsm_state102 : begin
            ap_NS_fsm = ap_ST_fsm_state103;
        end
        ap_ST_fsm_state103 : begin
            ap_NS_fsm = ap_ST_fsm_state104;
        end
        ap_ST_fsm_state104 : begin
            ap_NS_fsm = ap_ST_fsm_state105;
        end
        ap_ST_fsm_state105 : begin
            ap_NS_fsm = ap_ST_fsm_state106;
        end
        ap_ST_fsm_state106 : begin
            ap_NS_fsm = ap_ST_fsm_state107;
        end
        ap_ST_fsm_state107 : begin
            ap_NS_fsm = ap_ST_fsm_state108;
        end
        ap_ST_fsm_state108 : begin
            ap_NS_fsm = ap_ST_fsm_state109;
        end
        ap_ST_fsm_state109 : begin
            ap_NS_fsm = ap_ST_fsm_state110;
        end
        ap_ST_fsm_state110 : begin
            ap_NS_fsm = ap_ST_fsm_state111;
        end
        ap_ST_fsm_state111 : begin
            ap_NS_fsm = ap_ST_fsm_state112;
        end
        ap_ST_fsm_state112 : begin
            ap_NS_fsm = ap_ST_fsm_state113;
        end
        ap_ST_fsm_state113 : begin
            ap_NS_fsm = ap_ST_fsm_state114;
        end
        ap_ST_fsm_state114 : begin
            ap_NS_fsm = ap_ST_fsm_state115;
        end
        ap_ST_fsm_state115 : begin
            ap_NS_fsm = ap_ST_fsm_state116;
        end
        ap_ST_fsm_state116 : begin
            ap_NS_fsm = ap_ST_fsm_state117;
        end
        ap_ST_fsm_state117 : begin
            ap_NS_fsm = ap_ST_fsm_state118;
        end
        ap_ST_fsm_state118 : begin
            ap_NS_fsm = ap_ST_fsm_state119;
        end
        ap_ST_fsm_state119 : begin
            ap_NS_fsm = ap_ST_fsm_state120;
        end
        ap_ST_fsm_state120 : begin
            ap_NS_fsm = ap_ST_fsm_state121;
        end
        ap_ST_fsm_state121 : begin
            ap_NS_fsm = ap_ST_fsm_state122;
        end
        ap_ST_fsm_state122 : begin
            ap_NS_fsm = ap_ST_fsm_state123;
        end
        ap_ST_fsm_state123 : begin
            ap_NS_fsm = ap_ST_fsm_state124;
        end
        ap_ST_fsm_state124 : begin
            ap_NS_fsm = ap_ST_fsm_state125;
        end
        ap_ST_fsm_state125 : begin
            ap_NS_fsm = ap_ST_fsm_state126;
        end
        ap_ST_fsm_state126 : begin
            ap_NS_fsm = ap_ST_fsm_state127;
        end
        ap_ST_fsm_state127 : begin
            ap_NS_fsm = ap_ST_fsm_state128;
        end
        ap_ST_fsm_state128 : begin
            ap_NS_fsm = ap_ST_fsm_state129;
        end
        ap_ST_fsm_state129 : begin
            ap_NS_fsm = ap_ST_fsm_state130;
        end
        ap_ST_fsm_state130 : begin
            ap_NS_fsm = ap_ST_fsm_state131;
        end
        ap_ST_fsm_state131 : begin
            ap_NS_fsm = ap_ST_fsm_state132;
        end
        ap_ST_fsm_state132 : begin
            ap_NS_fsm = ap_ST_fsm_state133;
        end
        ap_ST_fsm_state133 : begin
            ap_NS_fsm = ap_ST_fsm_state134;
        end
        ap_ST_fsm_state134 : begin
            ap_NS_fsm = ap_ST_fsm_state135;
        end
        ap_ST_fsm_state135 : begin
            ap_NS_fsm = ap_ST_fsm_state136;
        end
        ap_ST_fsm_state136 : begin
            ap_NS_fsm = ap_ST_fsm_state137;
        end
        ap_ST_fsm_state137 : begin
            ap_NS_fsm = ap_ST_fsm_state138;
        end
        ap_ST_fsm_state138 : begin
            ap_NS_fsm = ap_ST_fsm_state139;
        end
        ap_ST_fsm_state139 : begin
            ap_NS_fsm = ap_ST_fsm_state140;
        end
        ap_ST_fsm_state140 : begin
            ap_NS_fsm = ap_ST_fsm_state141;
        end
        ap_ST_fsm_state141 : begin
            ap_NS_fsm = ap_ST_fsm_state142;
        end
        ap_ST_fsm_state142 : begin
            ap_NS_fsm = ap_ST_fsm_state143;
        end
        ap_ST_fsm_state143 : begin
            ap_NS_fsm = ap_ST_fsm_state144;
        end
        ap_ST_fsm_state144 : begin
            if (((gmem_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state144))) begin
                ap_NS_fsm = ap_ST_fsm_state145;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state144;
            end
        end
        ap_ST_fsm_state145 : begin
            ap_NS_fsm = ap_ST_fsm_state146;
        end
        ap_ST_fsm_state146 : begin
            if (((grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state146))) begin
                ap_NS_fsm = ap_ST_fsm_state147;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state146;
            end
        end
        ap_ST_fsm_state147 : begin
            ap_NS_fsm = ap_ST_fsm_state148;
        end
        ap_ST_fsm_state148 : begin
            ap_NS_fsm = ap_ST_fsm_state149;
        end
        ap_ST_fsm_state149 : begin
            ap_NS_fsm = ap_ST_fsm_state150;
        end
        ap_ST_fsm_state150 : begin
            ap_NS_fsm = ap_ST_fsm_state151;
        end
        ap_ST_fsm_state151 : begin
            ap_NS_fsm = ap_ST_fsm_state152;
        end
        ap_ST_fsm_state152 : begin
            ap_NS_fsm = ap_ST_fsm_state153;
        end
        ap_ST_fsm_state153 : begin
            ap_NS_fsm = ap_ST_fsm_state154;
        end
        ap_ST_fsm_state154 : begin
            ap_NS_fsm = ap_ST_fsm_state155;
        end
        ap_ST_fsm_state155 : begin
            ap_NS_fsm = ap_ST_fsm_state156;
        end
        ap_ST_fsm_state156 : begin
            ap_NS_fsm = ap_ST_fsm_state157;
        end
        ap_ST_fsm_state157 : begin
            ap_NS_fsm = ap_ST_fsm_state158;
        end
        ap_ST_fsm_state158 : begin
            ap_NS_fsm = ap_ST_fsm_state159;
        end
        ap_ST_fsm_state159 : begin
            ap_NS_fsm = ap_ST_fsm_state160;
        end
        ap_ST_fsm_state160 : begin
            ap_NS_fsm = ap_ST_fsm_state161;
        end
        ap_ST_fsm_state161 : begin
            ap_NS_fsm = ap_ST_fsm_state162;
        end
        ap_ST_fsm_state162 : begin
            ap_NS_fsm = ap_ST_fsm_state163;
        end
        ap_ST_fsm_state163 : begin
            ap_NS_fsm = ap_ST_fsm_state164;
        end
        ap_ST_fsm_state164 : begin
            ap_NS_fsm = ap_ST_fsm_state165;
        end
        ap_ST_fsm_state165 : begin
            ap_NS_fsm = ap_ST_fsm_state166;
        end
        ap_ST_fsm_state166 : begin
            ap_NS_fsm = ap_ST_fsm_state167;
        end
        ap_ST_fsm_state167 : begin
            ap_NS_fsm = ap_ST_fsm_state168;
        end
        ap_ST_fsm_state168 : begin
            ap_NS_fsm = ap_ST_fsm_state169;
        end
        ap_ST_fsm_state169 : begin
            ap_NS_fsm = ap_ST_fsm_state170;
        end
        ap_ST_fsm_state170 : begin
            ap_NS_fsm = ap_ST_fsm_state171;
        end
        ap_ST_fsm_state171 : begin
            ap_NS_fsm = ap_ST_fsm_state172;
        end
        ap_ST_fsm_state172 : begin
            ap_NS_fsm = ap_ST_fsm_state173;
        end
        ap_ST_fsm_state173 : begin
            ap_NS_fsm = ap_ST_fsm_state174;
        end
        ap_ST_fsm_state174 : begin
            ap_NS_fsm = ap_ST_fsm_state175;
        end
        ap_ST_fsm_state175 : begin
            ap_NS_fsm = ap_ST_fsm_state176;
        end
        ap_ST_fsm_state176 : begin
            ap_NS_fsm = ap_ST_fsm_state177;
        end
        ap_ST_fsm_state177 : begin
            ap_NS_fsm = ap_ST_fsm_state178;
        end
        ap_ST_fsm_state178 : begin
            ap_NS_fsm = ap_ST_fsm_state179;
        end
        ap_ST_fsm_state179 : begin
            ap_NS_fsm = ap_ST_fsm_state180;
        end
        ap_ST_fsm_state180 : begin
            ap_NS_fsm = ap_ST_fsm_state181;
        end
        ap_ST_fsm_state181 : begin
            ap_NS_fsm = ap_ST_fsm_state182;
        end
        ap_ST_fsm_state182 : begin
            ap_NS_fsm = ap_ST_fsm_state183;
        end
        ap_ST_fsm_state183 : begin
            ap_NS_fsm = ap_ST_fsm_state184;
        end
        ap_ST_fsm_state184 : begin
            ap_NS_fsm = ap_ST_fsm_state185;
        end
        ap_ST_fsm_state185 : begin
            ap_NS_fsm = ap_ST_fsm_state186;
        end
        ap_ST_fsm_state186 : begin
            ap_NS_fsm = ap_ST_fsm_state187;
        end
        ap_ST_fsm_state187 : begin
            ap_NS_fsm = ap_ST_fsm_state188;
        end
        ap_ST_fsm_state188 : begin
            ap_NS_fsm = ap_ST_fsm_state189;
        end
        ap_ST_fsm_state189 : begin
            ap_NS_fsm = ap_ST_fsm_state190;
        end
        ap_ST_fsm_state190 : begin
            ap_NS_fsm = ap_ST_fsm_state191;
        end
        ap_ST_fsm_state191 : begin
            ap_NS_fsm = ap_ST_fsm_state192;
        end
        ap_ST_fsm_state192 : begin
            ap_NS_fsm = ap_ST_fsm_state193;
        end
        ap_ST_fsm_state193 : begin
            ap_NS_fsm = ap_ST_fsm_state194;
        end
        ap_ST_fsm_state194 : begin
            ap_NS_fsm = ap_ST_fsm_state195;
        end
        ap_ST_fsm_state195 : begin
            ap_NS_fsm = ap_ST_fsm_state196;
        end
        ap_ST_fsm_state196 : begin
            ap_NS_fsm = ap_ST_fsm_state197;
        end
        ap_ST_fsm_state197 : begin
            ap_NS_fsm = ap_ST_fsm_state198;
        end
        ap_ST_fsm_state198 : begin
            ap_NS_fsm = ap_ST_fsm_state199;
        end
        ap_ST_fsm_state199 : begin
            ap_NS_fsm = ap_ST_fsm_state200;
        end
        ap_ST_fsm_state200 : begin
            ap_NS_fsm = ap_ST_fsm_state201;
        end
        ap_ST_fsm_state201 : begin
            ap_NS_fsm = ap_ST_fsm_state202;
        end
        ap_ST_fsm_state202 : begin
            ap_NS_fsm = ap_ST_fsm_state203;
        end
        ap_ST_fsm_state203 : begin
            ap_NS_fsm = ap_ST_fsm_state204;
        end
        ap_ST_fsm_state204 : begin
            ap_NS_fsm = ap_ST_fsm_state205;
        end
        ap_ST_fsm_state205 : begin
            ap_NS_fsm = ap_ST_fsm_state206;
        end
        ap_ST_fsm_state206 : begin
            ap_NS_fsm = ap_ST_fsm_state207;
        end
        ap_ST_fsm_state207 : begin
            ap_NS_fsm = ap_ST_fsm_state208;
        end
        ap_ST_fsm_state208 : begin
            ap_NS_fsm = ap_ST_fsm_state209;
        end
        ap_ST_fsm_state209 : begin
            ap_NS_fsm = ap_ST_fsm_state210;
        end
        ap_ST_fsm_state210 : begin
            ap_NS_fsm = ap_ST_fsm_state211;
        end
        ap_ST_fsm_state211 : begin
            ap_NS_fsm = ap_ST_fsm_state212;
        end
        ap_ST_fsm_state212 : begin
            ap_NS_fsm = ap_ST_fsm_state213;
        end
        ap_ST_fsm_state213 : begin
            ap_NS_fsm = ap_ST_fsm_state214;
        end
        ap_ST_fsm_state214 : begin
            if ((~((gmem_BVALID == 1'b0) & (icmp_ln83_reg_443 == 1'd1)) & (1'b1 == ap_CS_fsm_state214))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state214;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln76_1_fu_204_p2 = (zext_ln76_fu_200_p1 + 24'd1);

assign add_ln76_2_fu_228_p2 = (indvar_fu_108 + 24'd1);

assign add_ln76_fu_184_p2 = ($signed(trunc_ln76_fu_180_p1) + $signed(31'd2147483647));

assign add_ln80_1_fu_258_p2 = (zext_ln80_fu_249_p1 + out_r);

assign add_ln80_2_fu_263_p2 = (zext_ln80_fu_249_p1 + in1);

assign add_ln80_3_fu_268_p2 = (i_fu_104 + 32'd256);

assign add_ln80_fu_253_p2 = (zext_ln80_fu_249_p1 + in2);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state144 = ap_CS_fsm[32'd143];

assign ap_CS_fsm_state145 = ap_CS_fsm[32'd144];

assign ap_CS_fsm_state146 = ap_CS_fsm[32'd145];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state214 = ap_CS_fsm[32'd213];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state73 = ap_CS_fsm[32'd72];

assign ap_CS_fsm_state74 = ap_CS_fsm[32'd73];

assign ap_CS_fsm_state75 = ap_CS_fsm[32'd74];

always @ (*) begin
    ap_block_state1 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

always @ (*) begin
    ap_block_state214 = ((gmem_BVALID == 1'b0) & (icmp_ln83_reg_443 == 1'd1));
end

assign chunk_size_fu_292_p3 = ((icmp_ln80_fu_274_p2[0:0] == 1'b1) ? sub_ln80_fu_287_p2 : 32'd256);

assign grp_krnl_vadd_Pipeline_read1_fu_155_ap_start = grp_krnl_vadd_Pipeline_read1_fu_155_ap_start_reg;

assign grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_ap_start = grp_krnl_vadd_Pipeline_vadd_writeC_fu_164_ap_start_reg;

assign icmp_ln76_1_fu_223_p2 = ((indvar_fu_108 == add_ln76_1_reg_417) ? 1'b1 : 1'b0);

assign icmp_ln76_fu_174_p2 = (($signed(size) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign icmp_ln80_fu_274_p2 = ((add_ln80_3_fu_268_p2 > size) ? 1'b1 : 1'b0);

assign icmp_ln83_fu_300_p2 = (($signed(chunk_size_fu_292_p3) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign sext_ln83_fu_336_p1 = $signed(trunc_ln2_reg_447);

assign sext_ln90_1_fu_360_p1 = $signed(trunc_ln90_1_reg_459);

assign sext_ln90_fu_350_p1 = $signed(trunc_ln3_reg_453);

assign shl_ln_fu_241_p3 = {{trunc_ln80_fu_237_p1}, {10'd0}};

assign sub_ln80_fu_287_p2 = (size - zext_ln81_fu_283_p1);

assign trunc_ln76_1_fu_190_p4 = {{add_ln76_fu_184_p2[30:8]}};

assign trunc_ln76_fu_180_p1 = size[30:0];

assign trunc_ln80_fu_237_p1 = indvar_fu_108[22:0];

assign trunc_ln81_fu_279_p1 = i_fu_104[30:0];

assign trunc_ln83_fu_346_p1 = chunk_size_reg_435[30:0];

assign zext_ln76_fu_200_p1 = trunc_ln76_1_fu_190_p4;

assign zext_ln80_fu_249_p1 = shl_ln_fu_241_p3;

assign zext_ln81_fu_283_p1 = trunc_ln81_fu_279_p1;

endmodule //krnl_vadd
