# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/mateusz/KV260/hardware/hardware.srcs/sources_1/bd/hardware/ip/hardware_proc_sys_reset_0_0/hardware_proc_sys_reset_0_0.xci
# IP: The module: 'hardware_proc_sys_reset_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/mateusz/KV260/hardware/hardware.gen/sources_1/bd/hardware/ip/hardware_proc_sys_reset_0_0/hardware_proc_sys_reset_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'hardware_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/mateusz/KV260/hardware/hardware.gen/sources_1/bd/hardware/ip/hardware_proc_sys_reset_0_0/hardware_proc_sys_reset_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'hardware_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/mateusz/KV260/hardware/hardware.gen/sources_1/bd/hardware/ip/hardware_proc_sys_reset_0_0/hardware_proc_sys_reset_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hardware_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/mateusz/KV260/hardware/hardware.srcs/sources_1/bd/hardware/ip/hardware_proc_sys_reset_0_0/hardware_proc_sys_reset_0_0.xci
# IP: The module: 'hardware_proc_sys_reset_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/mateusz/KV260/hardware/hardware.gen/sources_1/bd/hardware/ip/hardware_proc_sys_reset_0_0/hardware_proc_sys_reset_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'hardware_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/mateusz/KV260/hardware/hardware.gen/sources_1/bd/hardware/ip/hardware_proc_sys_reset_0_0/hardware_proc_sys_reset_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'hardware_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/mateusz/KV260/hardware/hardware.gen/sources_1/bd/hardware/ip/hardware_proc_sys_reset_0_0/hardware_proc_sys_reset_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hardware_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
