# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/mateusz/KV260/hardware/hardware.srcs/sources_1/bd/hardware/ip/hardware_auto_pc_0/hardware_auto_pc_0.xci
# IP: The module: 'hardware_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/mateusz/KV260/hardware/hardware.gen/sources_1/bd/hardware/ip/hardware_auto_pc_0/hardware_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hardware_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/mateusz/KV260/hardware/hardware.srcs/sources_1/bd/hardware/ip/hardware_auto_pc_0/hardware_auto_pc_0.xci
# IP: The module: 'hardware_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/mateusz/KV260/hardware/hardware.gen/sources_1/bd/hardware/ip/hardware_auto_pc_0/hardware_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hardware_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
