# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/mateusz/KV260/hardware/hardware.srcs/sources_1/bd/hardware/ip/hardware_DPUCZDX8G_0_1/hardware_DPUCZDX8G_0_1.xci
# IP: The module: 'hardware_DPUCZDX8G_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/mateusz/KV260/hardware/hardware.gen/sources_1/bd/hardware/ip/hardware_DPUCZDX8G_0_1/xci/sfm/fp_add/fp_add.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fp_add || ORIG_REF_NAME==fp_add} -quiet] -quiet

# IP: /home/mateusz/KV260/hardware/hardware.gen/sources_1/bd/hardware/ip/hardware_DPUCZDX8G_0_1/xci/sfm/fp_acc/fp_acc.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fp_acc || ORIG_REF_NAME==fp_acc} -quiet] -quiet

# IP: /home/mateusz/KV260/hardware/hardware.gen/sources_1/bd/hardware/ip/hardware_DPUCZDX8G_0_1/xci/sfm/fp_div/fp_div.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fp_div || ORIG_REF_NAME==fp_div} -quiet] -quiet

# IP: /home/mateusz/KV260/hardware/hardware.gen/sources_1/bd/hardware/ip/hardware_DPUCZDX8G_0_1/xci/sfm/fp_convert/fp_convert.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fp_convert || ORIG_REF_NAME==fp_convert} -quiet] -quiet

# IP: /home/mateusz/KV260/hardware/hardware.gen/sources_1/bd/hardware/ip/hardware_DPUCZDX8G_0_1/xci/sfm/fp_exp/fp_exp.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fp_exp || ORIG_REF_NAME==fp_exp} -quiet] -quiet

# XDC: /home/mateusz/KV260/hardware/hardware.gen/sources_1/bd/hardware/ip/hardware_DPUCZDX8G_0_1/hardware_DPUCZDX8G_0_1_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'hardware_DPUCZDX8G_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/mateusz/KV260/hardware/hardware.gen/sources_1/bd/hardware/ip/hardware_DPUCZDX8G_0_1/hardware_DPUCZDX8G_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'hardware_DPUCZDX8G_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/mateusz/KV260/hardware/hardware.srcs/sources_1/bd/hardware/ip/hardware_DPUCZDX8G_0_1/hardware_DPUCZDX8G_0_1.xci
# IP: The module: 'hardware_DPUCZDX8G_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/mateusz/KV260/hardware/hardware.gen/sources_1/bd/hardware/ip/hardware_DPUCZDX8G_0_1/xci/sfm/fp_add/fp_add.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fp_add || ORIG_REF_NAME==fp_add} -quiet] -quiet

# IP: /home/mateusz/KV260/hardware/hardware.gen/sources_1/bd/hardware/ip/hardware_DPUCZDX8G_0_1/xci/sfm/fp_acc/fp_acc.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fp_acc || ORIG_REF_NAME==fp_acc} -quiet] -quiet

# IP: /home/mateusz/KV260/hardware/hardware.gen/sources_1/bd/hardware/ip/hardware_DPUCZDX8G_0_1/xci/sfm/fp_div/fp_div.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fp_div || ORIG_REF_NAME==fp_div} -quiet] -quiet

# IP: /home/mateusz/KV260/hardware/hardware.gen/sources_1/bd/hardware/ip/hardware_DPUCZDX8G_0_1/xci/sfm/fp_convert/fp_convert.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fp_convert || ORIG_REF_NAME==fp_convert} -quiet] -quiet

# IP: /home/mateusz/KV260/hardware/hardware.gen/sources_1/bd/hardware/ip/hardware_DPUCZDX8G_0_1/xci/sfm/fp_exp/fp_exp.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fp_exp || ORIG_REF_NAME==fp_exp} -quiet] -quiet

# XDC: /home/mateusz/KV260/hardware/hardware.gen/sources_1/bd/hardware/ip/hardware_DPUCZDX8G_0_1/hardware_DPUCZDX8G_0_1_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'hardware_DPUCZDX8G_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/mateusz/KV260/hardware/hardware.gen/sources_1/bd/hardware/ip/hardware_DPUCZDX8G_0_1/hardware_DPUCZDX8G_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'hardware_DPUCZDX8G_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
