# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "E:/KV260/package/binary_container_1.build/link/vivado/vpl/prj/prj.runs/synth_1/system_wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param bd.ForceAppCoreUpgrade 1
set_param general.maxThreads 1
set_param compiler.enablePerformanceTrace 1
set_param project.enablePRFlowIPI 1
set_param project.gatelevelSubdesign 1
set_param place.ultrathreadsUsed 0
set_param hd.Visual 0
set_param bd.enable_dpa 1
set_param bd.debug_profile.script E:/KV260/package/binary_container_1.build/link/vivado/vpl/.local/debug_profile_automation.tcl
set_param project.loadTopLevelOOCConstrs 1
set_msg_config -id {HDL-1065} -limit 10000
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xck26-sfvc784-2LV-c
set_property tool_flow SDx [current_project]

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/KV260/package/binary_container_1.build/link/vivado/vpl/prj/prj.cache/wt [current_project]
set_property parent.project_path E:/KV260/package/binary_container_1.build/link/vivado/vpl/prj/prj.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:kv260:part0:1.1 [current_project]
set_property board_connections {som240_1_connector xilinx.com:som240:som240_1_connector:1.0} [current_project]
set_property ip_repo_paths {
  e:/KV260/package/binary_container_1.build/link/int/xo/ip_repo/xilinx_com_hls_krnl_vadd_1_0
  f:/Vitis/Vitis/2021.1/data/cache/xilinx
  e:/KV260/package/binary_container_1.build/link/vivado/vpl/.local/hw_platform/ipcache
  f:/Vitis/Vitis/2021.1/data/ip
} [current_project]
update_ip_catalog
set_property ip_output_repo e:/KV260/package/binary_container_1.build/link/vivado/vpl/KV260package.ipcache [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib E:/KV260/package/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/system/hdl/system_wrapper.v
add_files E:/KV260/package/binary_container_1.build/link/vivado/vpl/prj/prj.srcs/sources_1/bd/system/system.bd
set_property used_in_implementation false [get_files -all e:/KV260/package/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/system/ip/system_zynq_ultra_ps_e_0_0/system_zynq_ultra_ps_e_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/KV260/package/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/system/ip/system_zynq_ultra_ps_e_0_0/system_zynq_ultra_ps_e_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/KV260/package/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/KV260/package/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/KV260/package/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/KV260/package/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/system/ip/system_proc_sys_reset_0_0/system_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/KV260/package/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/system/ip/system_proc_sys_reset_0_0/system_proc_sys_reset_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/KV260/package/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/system/ip/system_proc_sys_reset_0_0/system_proc_sys_reset_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/KV260/package/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/system/ip/system_axi_intc_0_0/system_axi_intc_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/KV260/package/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/system/ip/system_axi_intc_0_0/system_axi_intc_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/KV260/package/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/system/ip/system_axi_intc_0_0/system_axi_intc_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/KV260/package/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/system/ip/system_axi_gpio_0_0/system_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/KV260/package/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/system/ip/system_axi_gpio_0_0/system_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/KV260/package/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/system/ip/system_axi_gpio_0_0/system_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/KV260/package/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/system/ip/system_axi_iic_0_0/system_axi_iic_0_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/KV260/package/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/system/ip/system_axi_iic_0_0/system_axi_iic_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/KV260/package/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/system/ip/system_xbar_0/system_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/KV260/package/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/system/ip/system_xbar_1/system_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/KV260/package/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/system/ip/system_krnl_vadd_1_0/constraints/krnl_vadd_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/KV260/package/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/system/ip/system_m01_regslice_0/system_m01_regslice_0_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/KV260/package/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/system/ip/system_m01_regslice_0/system_m01_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/KV260/package/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/system/ip/system_auto_pc_0/system_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/KV260/package/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/system/ip/system_auto_pc_1/system_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/KV260/package/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/system/ip/system_auto_pc_2/system_auto_pc_2_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/KV260/package/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/system/ip/system_auto_pc_3/system_auto_pc_3_ooc.xdc]
set_property used_in_synthesis false [get_files -all e:/KV260/package/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/system/ip/system_auto_us_0/system_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/KV260/package/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/system/ip/system_auto_us_0/system_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/KV260/package/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/system/ip/system_auto_us_0/system_auto_us_0_ooc.xdc]
set_property used_in_implementation false [get_files -all E:/KV260/package/binary_container_1.build/link/vivado/vpl/prj/prj.gen/sources_1/bd/system/system_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc -mode out_of_context E:/KV260/package/binary_container_1.build/link/vivado/vpl/output/system_ooc_copy.xdc
set_property used_in_implementation false [get_files E:/KV260/package/binary_container_1.build/link/vivado/vpl/output/system_ooc_copy.xdc]
set_property processing_order EARLY [get_files E:/KV260/package/binary_container_1.build/link/vivado/vpl/output/system_ooc_copy.xdc]

read_xdc E:/KV260/package/binary_container_1.build/link/vivado/vpl/prj/prj.srcs/constrs_1/imports/new/system.xdc
set_property used_in_implementation false [get_files E:/KV260/package/binary_container_1.build/link/vivado/vpl/prj/prj.srcs/constrs_1/imports/new/system.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top system_wrapper -part xck26-sfvc784-2LV-c
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef system_wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
